#ifndef ULIB_UUNICODE_H
#define ULIB_UUNICODE_H

// The Unicode NAMES and BLOCKS of the characters this system's fonts can
// draw ("LATIN SMALL LETTER E WITH ACUTE", "Latin-1 Supplement"), and the
// UTF-8 encoding of a code point. The Character Map's data; GNOME
// Characters reads the same from its own compiled database.
//
// The data is two text files in /usr/share/unicode, generated by
// tools/gen_unicode_names.py for exactly the code points the shipped
// fonts map. Loaded on first use and kept; a missing file is "no names",
// never an error -- a character is still its code point.
#include <stddef.h>
#include <stdint.h>

struct uunicode_block {
    uint32_t lo, hi;
    const char *name;
};

// The name of `cp`, or NULL when the data has none for it.
const char *uunicode_name(uint32_t cp);

// Every named code point, ascending: index 0..uunicode_named_count()-1.
int      uunicode_named_count(void);
uint32_t uunicode_named(int i);

int uunicode_block_count(void);
const struct uunicode_block *uunicode_block(int i);
// The index of the block holding `cp`, or -1.
int uunicode_block_of(uint32_t cp);

// Every named code point matching `q`, ascending, up to `cap`; returns the
// count found (which may exceed cap). A query is one of:
//   "U+2192", "2192"     the code point itself (also a hex number alone)
//   one character        that character, in UTF-8 or as one Latin-1 byte
//   words                every name with a word STARTING with each of
//                        them, case ignored ("arrow right" finds
//                        RIGHTWARDS ARROW; "e" does not find LETTER)
int uunicode_search(const char *q, uint32_t *out, int cap);

// `cp` as UTF-8 into `out` (4 bytes and a NUL); returns the byte count,
// 0 for a value that is not a scalar value (a surrogate, past U+10FFFF).
int uunicode_utf8(uint32_t cp, char out[5]);
// The first code point of a UTF-8 string, and its length in `*len`;
// U+FFFD and length 1 for a malformed byte.
uint32_t uunicode_utf8_decode(const char *s, int *len);

#endif
