#ifndef INPUT_H
#define INPUT_H

#include <stdint.h>

// The input core: one canonical event vocabulary, and a registry of the
// devices that produce it.
//
// WHY THIS EXISTS
// ---------------
// There used to be no seam at all. `i8042_poll()` fed bytes straight
// into `keyboard_feed_byte()` and `mouse_feed_byte()`, each of which
// owned both the decoding AND the state every consumer reads -- so a
// second kind of input device had nowhere to plug in, and "add a
// driver" meant "edit the PS/2 driver". virtio-input is the second
// kind; USB HID will be the third.
//
// THE CANONICAL EVENT IS evdev-SHAPED, and that choice is the whole
// design. A key is a KEYCODE (`KEY_*` below, Linux's evdev numbering),
// not an AT scancode; a pointer reports relative or absolute motion,
// a button mask and wheel notches. Linux made the same call for the
// same reason -- `atkbd` translates AT set 1 INTO keycodes, USB HID
// translates usages into them, and virtio-input carries them natively
// because its events ARE `struct input_event`. Windows does the job
// with HID as the internal model and a legacy 8042 mapper beside it.
// Either way the PC encoding is a SOURCE format, never the internal
// one: a USB keyboard has no scancodes to speak of, and making it
// invent some would be inventing a legacy it never had.
//
// WHAT PS/2 DOES, STATED PLAINLY. The 8042 driver does NOT round-trip
// through this vocabulary: it already speaks set 1, and the layout
// tables (`/etc/kbs/*`, generated by tools/gen_kbs.py) are keyed on set
// 1, so it feeds its own state machine directly. New sources come in
// through input_report_key(), which translates keycode -> set 1 once
// and joins the same path. That translation table is the seam's only
// piece of legacy, and it disappears when the layout files are re-keyed
// to evdev codes -- which is a follow-on, not a prerequisite (see
// docs/roadmap.md). The CONTRACT for anything new is evdev either way.

// --- capabilities -----------------------------------------------------
#define INPUT_CAP_KEYS  (1u << 0)  // reports keycodes
#define INPUT_CAP_REL   (1u << 1)  // relative pointer motion
#define INPUT_CAP_ABS   (1u << 2)  // absolute pointer position (a tablet)
#define INPUT_CAP_WHEEL (1u << 3)

// A device that produces input. Registered by its own driver, listed by
// `lsdev`, and polled from scheduler_idle() if it has a poll function.
//
// `poll` is optional and exists for a device with no interrupt of its
// own -- a source that is interrupt-driven leaves it NULL and reports
// from its handler instead. Keeping both shapes in one registry is what
// stops "how does this device get serviced?" being a different question
// per driver.
struct input_source {
    const char *name;        // "ps2-keyboard", "virtio-keyboard"

    // The DRIVER behind it -- "i8042", "usb-hid". One driver commonly
    // presents several sources (a keyboard and a mouse on one i8042),
    // which is why it is not `name`. input_register_source() reports it
    // to `lsdrv`.
    const char *driver;
    uint32_t caps;
    void (*poll)(void);      // may be NULL

    // A poll is PERIODIC by default: a tickless idle wakes every
    // INPUT_POLL_MS to run it, because a polled device has nothing else
    // to wake the CPU. Set this when the poll is only a safety net
    // behind an interrupt that is trusted -- an MSI, which cannot be the
    // dead shared line a BIOS INTx can be -- and it runs on wakes alone.
    uint8_t poll_on_wake;

    // The IRQ line this device is serviced on, or 0 when it is polled.
    // Recorded so "how does this device get serviced?" is answerable
    // from OUTSIDE the kernel -- `lsdev` prints it. It used to be a boot
    // log line, which is unreadable by the time anything asks: the klog
    // is a ring buffer and a desktop rolls it over in seconds.
    uint8_t irq;

    // ...or the MSI/MSI-X VECTOR it is delivered on, when it is not on a
    // line at all. Its own field rather than reusing `irq` because the
    // two are different namespaces -- vector 48 and IRQ 48 are not the
    // same thing -- and because `irq == 0` already means "polled", which
    // an MSI-driven device very much is not. lsdev prints whichever is
    // set.
    uint8_t msi_vector;

    // Sets the keyboard's lock LEDs (INPUT_LED_*), or NULL for a source
    // with none it can drive. MUST NOT BLOCK: it is called from the key
    // handler, which runs in the keyboard's own interrupt.
    void (*set_leds)(uint8_t leds);
};

// The lock lights, in the PS/2 "set LEDs" (0xED) byte's own order.
#define INPUT_LED_SCROLL 0x01
#define INPUT_LED_NUM    0x02
#define INPUT_LED_CAPS   0x04

// Tells every source that can show them. Safe from an interrupt handler.
void input_set_leds(uint8_t leds);

void input_register_source(const struct input_source *src);

// Removes a registered source -- USB hot-unplug is why this exists.
// The caller must first make sure the source's poll can never fire
// again (its own in_use flag); see the comment in input.c.
void input_unregister_source(const struct input_source *src);

int  input_source_count(void);
const struct input_source *input_source_at(int index);

// Runs every registered source's poll(). Called from scheduler_idle(),
// the kernel's one owner of idle work.
void input_poll_sources(void);

// --- reporting, from a driver into the core ---------------------------
//
// These are the ONLY way a new device delivers input. Each is safe to
// call from an interrupt handler: they touch the same state the PS/2
// path does and do no more than it does there.

// A key went down (1) or up (0), by evdev keycode.
void input_report_key(uint16_t keycode, int down);

// **THERE IS NO KEYCODE-TO-SCANCODE TRANSLATION ANY MORE.** There was,
// and it is what this header used to spend a paragraph on: the layout
// tables were keyed on AT scancodes, so every non-PS/2 device had to be
// converted down into a legacy encoding by a hand-kept table -- which
// grew a hole (KEY_102ND, the ISO key carrying `|`) that made a
// pipeline untypeable on virtio-input and fine on PS/2. /etc/kbs is
// keyed on evdev keycodes now, so a keycode goes straight to
// keyboard_key_event() and there is nothing left to have a hole in.

// Relative pointer motion, in device counts. Speed and acceleration are
// applied by the pointer state, not by the caller.
//
// **dy IS UP-POSITIVE**, which is the PS/2 sense and the OPPOSITE of
// what most device protocols report. mouse_feed_rel() ends in
// `mouse_y -= dy` because it was written against a PS/2 mouse. evdev's
// REL_Y and a HID boot mouse both make positive mean DOWN the screen,
// so both virtio_input.c and input_usbhid.c negate on the way in. This was
// stated nowhere until a driver got it wrong, and the only way to find
// it was reading mouse.c -- so it is stated here now.
void input_report_rel(int dx, int dy);

// Absolute position, in the device's own axis range -- scaled to the
// screen here rather than by each driver, because the range is a
// property of the device and the screen size is not something a driver
// should have to track. This is the path a tablet or a touchscreen
// takes; `max_x`/`max_y` of 0 are ignored rather than dividing by zero.
void input_report_abs(int x, int y, int max_x, int max_y);

// Button mask: bit0 left, bit1 right, bit2 middle, bit3 SIDE, bit4
// EXTRA -- the encoding mouse_get_state() already reports. The two
// thumb bits were added 2026-09-19; a driver that reports only three
// is unaffected, and one that reports more has them dropped at
// mouse_feed_buttons().
void input_report_buttons(uint8_t mask);

// Wheel notches, positive = away from the user.
void input_report_wheel(int notches);

// --- evdev keycodes ---------------------------------------------------
//
// The numbers themselves are the kernel<->userland contract's
// (abi/input_keys.h), so a window asking for physical keys and this
// input core speak one list.
#include "input_keys.h"

// 1..83 are the AT set-1 make codes unchanged (see gen_kbs.py's note:
// XKB keycodes are evdev + 8, and evdev matches set 1 for this block).
#define INPUT_KEY_EVDEV_DIRECT_MAX 83

// ...AND THE THREE PLAIN SET-1 KEYS THAT SIT PAST THE END OF IT.
//
// The direct range stops at 83 (KP_DOT) because evdev 84 and 85 are not
// set-1 codes. But 86, 87 and 88 are again -- 0x56, 0x57, 0x58 -- so
// they need a mapping rather than the drop they were getting, and they
// are NOT behind an 0xE0 prefix, which is what makes them a different
// case from the EXTENDED table in input.c.
//
// **KEY_102ND IS THE ONE THAT MATTERS**: missing it meant a pipeline
// could not be typed AT ALL on an `INPUT=virtio` boot, while working
// perfectly on PS/2, because only the virtio path comes through here.
// See docs/decisions.md.

// Pointer buttons, evdev numbering.
//
// SIDE AND EXTRA ARE THE THUMB BUTTONS, and they are named for the
// POSITION rather than for "back" and "forward" because that is what
// the device reports -- what they MEAN is the application's decision,
// which is Wayland's split and Windows' (WM_XBUTTONDOWN carries
// XBUTTON1/2, and it is Explorer that reads them as navigation).
//
// X11 numbers these 8 and 9 because it spent 4..7 on the wheel. toy-os
// does not inherit that: the wheel is its own event here, so the bits
// below sit where evdev puts them.
#define INPUT_BTN_LEFT   0x110
#define INPUT_BTN_RIGHT  0x111
#define INPUT_BTN_MIDDLE 0x112
#define INPUT_BTN_SIDE   0x113
#define INPUT_BTN_EXTRA  0x114

#endif
