#ifndef INPUT_H
#define INPUT_H

#include <stdint.h>

// The input core: one canonical event vocabulary, and a registry of the
// devices that produce it.
//
// WHY THIS EXISTS
// ---------------
// There used to be no seam at all. `i8042_poll()` fed bytes straight
// into `keyboard_feed_byte()` and `mouse_feed_byte()`, each of which
// owned both the decoding AND the state every consumer reads -- so a
// second kind of input device had nowhere to plug in, and "add a
// driver" meant "edit the PS/2 driver". virtio-input is the second
// kind; USB HID will be the third.
//
// THE CANONICAL EVENT IS evdev-SHAPED, and that choice is the whole
// design. A key is a KEYCODE (`KEY_*` below, Linux's evdev numbering),
// not an AT scancode; a pointer reports relative or absolute motion,
// a button mask and wheel notches. Linux made the same call for the
// same reason -- `atkbd` translates AT set 1 INTO keycodes, USB HID
// translates usages into them, and virtio-input carries them natively
// because its events ARE `struct input_event`. Windows does the job
// with HID as the internal model and a legacy 8042 mapper beside it.
// Either way the PC encoding is a SOURCE format, never the internal
// one: a USB keyboard has no scancodes to speak of, and making it
// invent some would be inventing a legacy it never had.
//
// WHAT PS/2 DOES, STATED PLAINLY. The 8042 driver does NOT round-trip
// through this vocabulary: it already speaks set 1, and the layout
// tables (`/etc/kbs/*`, generated by tools/gen_kbs.py) are keyed on set
// 1, so it feeds its own state machine directly. New sources come in
// through input_report_key(), which translates keycode -> set 1 once
// and joins the same path. That translation table is the seam's only
// piece of legacy, and it disappears when the layout files are re-keyed
// to evdev codes -- which is a follow-on, not a prerequisite (see
// docs/roadmap.md). The CONTRACT for anything new is evdev either way.

// --- capabilities -----------------------------------------------------
#define INPUT_CAP_KEYS  (1u << 0)  // reports keycodes
#define INPUT_CAP_REL   (1u << 1)  // relative pointer motion
#define INPUT_CAP_ABS   (1u << 2)  // absolute pointer position (a tablet)
#define INPUT_CAP_WHEEL (1u << 3)

// A device that produces input. Registered by its own driver, listed by
// `lsdev`, and polled from scheduler_idle() if it has a poll function.
//
// `poll` is optional and exists for a device with no interrupt of its
// own -- a source that is interrupt-driven leaves it NULL and reports
// from its handler instead. Keeping both shapes in one registry is what
// stops "how does this device get serviced?" being a different question
// per driver.
struct input_source {
    const char *name;        // "ps2-keyboard", "virtio-keyboard"
    uint32_t caps;
    void (*poll)(void);      // may be NULL

    // The IRQ line this device is serviced on, or 0 when it is polled.
    // Recorded so "how does this device get serviced?" is answerable
    // from OUTSIDE the kernel -- `lsdev` prints it. It used to be a boot
    // log line, which is unreadable by the time anything asks: the klog
    // is a ring buffer and a desktop rolls it over in seconds.
    uint8_t irq;
};

void input_register_source(const struct input_source *src);

// Removes a registered source -- USB hot-unplug is why this exists.
// The caller must first make sure the source's poll can never fire
// again (its own in_use flag); see the comment in input.c.
void input_unregister_source(const struct input_source *src);

int  input_source_count(void);
const struct input_source *input_source_at(int index);

// Runs every registered source's poll(). Called from scheduler_idle(),
// the kernel's one owner of idle work.
void input_poll_sources(void);

// --- reporting, from a driver into the core ---------------------------
//
// These are the ONLY way a new device delivers input. Each is safe to
// call from an interrupt handler: they touch the same state the PS/2
// path does and do no more than it does there.

// A key went down (1) or up (0), by evdev keycode.
void input_report_key(uint16_t keycode, int down);

// **THERE IS NO KEYCODE-TO-SCANCODE TRANSLATION ANY MORE.** There was,
// and it is what this header used to spend a paragraph on: the layout
// tables were keyed on AT scancodes, so every non-PS/2 device had to be
// converted down into a legacy encoding by a hand-kept table -- which
// grew a hole (KEY_102ND, the ISO key carrying `|`) that made a
// pipeline untypeable on virtio-input and fine on PS/2. /etc/kbs is
// keyed on evdev keycodes now, so a keycode goes straight to
// keyboard_key_event() and there is nothing left to have a hole in.

// Relative pointer motion, in device counts. Speed and acceleration are
// applied by the pointer state, not by the caller.
//
// **dy IS UP-POSITIVE**, which is the PS/2 sense and the OPPOSITE of
// what most device protocols report. mouse_feed_rel() ends in
// `mouse_y -= dy` because it was written against a PS/2 mouse. evdev's
// REL_Y and a HID boot mouse both make positive mean DOWN the screen,
// so both virtio_input.c and usb_hid.c negate on the way in. This was
// stated nowhere until a driver got it wrong, and the only way to find
// it was reading mouse.c -- so it is stated here now.
void input_report_rel(int dx, int dy);

// Absolute position, in the device's own axis range -- scaled to the
// screen here rather than by each driver, because the range is a
// property of the device and the screen size is not something a driver
// should have to track. This is the path a tablet or a touchscreen
// takes; `max_x`/`max_y` of 0 are ignored rather than dividing by zero.
void input_report_abs(int x, int y, int max_x, int max_y);

// Button mask: bit0 left, bit1 right, bit2 middle -- the encoding
// mouse_get_state() already reports, so consumers are unchanged.
void input_report_buttons(uint8_t mask);

// Wheel notches, positive = away from the user.
void input_report_wheel(int notches);

// --- evdev keycodes ---------------------------------------------------
//
// Only the ones a driver here actually reports. The numbering is
// Linux's, so a table lifted from a HID or virtio specification lines
// up without adjustment -- which is the point of using it.
//
// THE `INPUT_` PREFIX IS NOT DECORATION. `keyboard.h` already has a
// `KEY_*` family, and it means something completely different: those
// are the codes this kernel's key RING carries (KEY_HOME is 0x9B, a
// value chosen to sit outside ASCII), while these are what the wire
// carries before any translation (INPUT_KEY_HOME is 102, Linux's
// number). Four of them collided outright when this header was first
// written, and a silent collision between two key vocabularies is a
// class of bug that would have surfaced as "Home does something odd on
// one keyboard".
#define INPUT_KEY_ESC 1
#define INPUT_KEY_ENTER 28
#define INPUT_KEY_LEFTCTRL 29
#define INPUT_KEY_LEFTSHIFT 42
#define INPUT_KEY_RIGHTSHIFT 54
#define INPUT_KEY_LEFTALT 56
#define INPUT_KEY_SPACE 57
#define INPUT_KEY_CAPSLOCK 58
// The numeric keypad, evdev's numbering, which is set-1's for this block
// (see INPUT_KEY_EVDEV_DIRECT_MAX below).
#define INPUT_KEY_KP7 71
#define INPUT_KEY_KP8 72
#define INPUT_KEY_KP9 73
#define INPUT_KEY_KPMINUS 74
#define INPUT_KEY_KP4 75
#define INPUT_KEY_KP5 76
#define INPUT_KEY_KP6 77
#define INPUT_KEY_KPPLUS 78
#define INPUT_KEY_KP1 79
#define INPUT_KEY_KP2 80
#define INPUT_KEY_KP3 81
#define INPUT_KEY_KP0 82
#define INPUT_KEY_KPDOT 83
#define INPUT_KEY_KPASTERISK 55
#define INPUT_KEY_NUMLOCK 69
#define INPUT_KEY_SCROLLLOCK 70
#define INPUT_KEY_SYSRQ 99      // Print Screen
#define INPUT_KEY_F1 59
#define INPUT_KEY_F2 60
#define INPUT_KEY_F3 61
#define INPUT_KEY_F4 62
#define INPUT_KEY_F5 63
#define INPUT_KEY_F6 64
#define INPUT_KEY_F7 65
#define INPUT_KEY_F8 66
#define INPUT_KEY_F9 67
#define INPUT_KEY_F10 68
// 1..83 are the AT set-1 make codes unchanged (see gen_kbs.py's note:
// XKB keycodes are evdev + 8, and evdev matches set 1 for this block).
#define INPUT_KEY_EVDEV_DIRECT_MAX 83

// ...AND THE THREE PLAIN SET-1 KEYS THAT SIT PAST THE END OF IT.
//
// The direct range stops at 83 (KP_DOT) because evdev 84 and 85 are not
// set-1 codes. But 86, 87 and 88 are again -- 0x56, 0x57, 0x58 -- so
// they need a mapping rather than the drop they were getting, and they
// are NOT behind an 0xE0 prefix, which is what makes them a different
// case from the EXTENDED table in input.c.
//
// **KEY_102ND IS THE ONE THAT MATTERS.** It is the extra key an ISO
// keyboard has between Left Shift and Z, and on every Nordic layout it
// carries `<`, `>` and -- with AltGr -- **`|`**. Missing it meant a
// pipeline could not be typed AT ALL on a `INPUT=virtio` boot, while
// working perfectly on PS/2, because only the virtio path comes through
// here. See docs/decisions.md.
#define INPUT_KEY_102ND 86
#define INPUT_KEY_F11 87
#define INPUT_KEY_F12 88

#define INPUT_KEY_KPENTER 96
#define INPUT_KEY_RIGHTCTRL 97
#define INPUT_KEY_KPSLASH 98
#define INPUT_KEY_RIGHTALT 100
#define INPUT_KEY_HOME 102
#define INPUT_KEY_UP 103
#define INPUT_KEY_PAGEUP 104
#define INPUT_KEY_LEFT 105
#define INPUT_KEY_RIGHT 106
#define INPUT_KEY_END 107
#define INPUT_KEY_DOWN 108
#define INPUT_KEY_PAGEDOWN 109
#define INPUT_KEY_INSERT 110
#define INPUT_KEY_DELETE 111
#define INPUT_KEY_LEFTMETA 125
#define INPUT_KEY_RIGHTMETA 126
#define INPUT_KEY_COMPOSE 127
#define INPUT_KEY_PAUSE 119

// Pointer buttons, evdev numbering.
#define INPUT_BTN_LEFT   0x110
#define INPUT_BTN_RIGHT  0x111
#define INPUT_BTN_MIDDLE 0x112

#endif
