#ifndef VERSION_H
#define VERSION_H

// GENERATED by tools/gen_version.sh -- run automatically as the first
// step of `make all`/`make iso` (see the Makefile). Don't hand-edit
// this file, it gets overwritten on the very next build.
//
// TOYOS_VERSION is a semver-ish string ("0.1.0-dev" while in
// development, "0.1.0" once released -- see VERSION at the repo root
// and tools/set_version.sh), shown by both the shell's `about` and
// the GUI About window. It's just whatever VERSION currently holds --
// this script doesn't change it. See docs/decisions.md for why this
// replaced the earlier per-change build-number scheme.
#define TOYOS_VERSION "0.2.0-dev"

#endif
