// A block device over a WINDOW of another block device -- one
// partition of a disk.
//
// Every LBA is shifted by base_lba and every transfer is bounds-checked
// against the window, so whatever mounts this sees a device that starts
// at sector 0 and ends at the partition's end. That is the whole trick,
// and it is why TFS3 needed no change to be mountable from a partition:
// it was already volume-relative behind a {base_lba, sector_count} seam
// (docs/tfs3-design.md, "Volumes and partitions"), and the volume it is
// handed is now genuinely the partition, so that seam stays at
// {0, sector_count} and means the right thing.
//
// WHY THE OFFSET LIVES HERE and not in the filesystem: this is where
// Linux and Windows both put it -- Linux gives each partition its own
// `struct block_device` carrying `bd_start_sect`, and the filesystem
// driver never learns partitions exist; Windows stacks `partmgr`
// between the disk driver and the volume. Teaching each backend to add
// an offset itself is the layering both moved away from, and it is work
// that would have to be repeated per backend.
//
// **THERE IS A POOL OF THESE NOW, NOT ONE.** It was a single static
// device because the active device was singular and a partition
// REPLACED its parent. Real mount points ended that: two filesystems
// are mounted at once and each needs its own volume alive at the same
// time, so a window is CREATED (blk_part_create) independently of
// whether anything makes it active (blk_part_register). Creating the
// same window twice returns the SAME device rather than burning a slot
// -- a mount and the boot scan both ask for partition 2, and two
// structs describing one window would give the mount table two names
// for one volume.
#include "block.h"
#include "kfmt.h" // k_snprintf
#include "klog.h"
#include <stddef.h>

// driver-none: partitions of a disk another driver drives

// One per partition that anything holds a device for. Four is MBR's
// limit and more than this OS's own disk uses (bios, esp, tfs3); the
// pool is bounded because a `struct block_device` plus its name is
// static storage, and an unbounded one would be a heap allocation with
// a lifetime nobody owns.
#define PART_SLOTS 8

struct part_slot {
    // The parent is BORROWED, not copied -- the disk drivers' device
    // structs are static and outlive everything here.
    const struct block_device *parent;
    uint32_t base;
    uint32_t sectors;
    int used;
    // Mutable and static, like block_virtio.c's: blk_register() keeps
    // the pointer rather than a copy, so the struct has to outlive the
    // call and the name has to stay valid for as long as `df` might
    // print it.
    char name[24];
    struct block_device dev;
};

static struct part_slot g_slots[PART_SLOTS];

// Which slot a device pointer belongs to, or NULL. The op callbacks
// below get no context argument (struct block_device is a plain table
// of function pointers, deliberately -- see block.h), so each slot
// needs its own set of thunks OR a way to recover itself from the
// device pointer it was called through. There is no such way: the
// callback does not receive the device.
//
// Hence the thunk table below: PART_SLOTS is small and fixed, so each
// slot gets its own tiny forwarding function generated by a macro. Ugly
// and honest, and it is what Linux avoids by passing the device into
// every block operation -- a shape this block layer deliberately does
// not have, because a filesystem here holds its device rather than
// being handed one per call.
static int slot_read(struct part_slot *s, uint32_t lba, int count, void *buf);
static int slot_write(struct part_slot *s, uint32_t lba, int count, const void *buf);
static int slot_trim(struct part_slot *s, uint32_t lba, uint32_t count);

// Compared in 64-bit throughout: lba + count overflows a uint32_t for a
// large enough lba, and an overflowed comparison passes. block_ram.c
// learned this one first.
static int range_ok(const struct part_slot *s, uint32_t lba, uint64_t count) {
    if (!s->parent || count == 0) return 0;
    return (uint64_t)lba + count <= (uint64_t)s->sectors;
}

static int slot_read(struct part_slot *s, uint32_t lba, int count, void *buf) {
    if (count <= 0 || !range_ok(s, lba, (uint64_t)count)) return 0;
    return s->parent->read_sectors(s->base + lba, count, buf);
}

static int slot_write(struct part_slot *s, uint32_t lba, int count, const void *buf) {
    if (count <= 0 || !range_ok(s, lba, (uint64_t)count)) return 0;
    return s->parent->write_sectors(s->base + lba, count, buf);
}

// TRIM is the one operation that must be CLAMPED as well as offset. A
// caller handing a count past the window's end would otherwise discard
// the next partition's data -- and TRIM is unrecoverable, so this
// refuses rather than truncating, the same call every parser in this
// tree makes.
static int slot_trim(struct part_slot *s, uint32_t lba, uint32_t count) {
    if (!range_ok(s, lba, (uint64_t)count)) return 0;
    return s->parent->trim(s->base + lba, count);
}

// Forwarded unchanged. This flushes the parent's WHOLE cache, not just
// this window -- broader than asked for, and deliberately so: a barrier
// that covers more than it promised is safe, one that covers less is
// the silent data-loss bug blk_flush()'s comment is about.
#define PART_THUNKS(i)                                                        \
    static uint32_t p##i##_count(void) { return g_slots[i].sectors; }         \
    static int p##i##_read(uint32_t l, int c, void *b) { return slot_read(&g_slots[i], l, c, b); }    \
    static int p##i##_write(uint32_t l, int c, const void *b) { return slot_write(&g_slots[i], l, c, b); } \
    static int p##i##_xfer(void) { return g_slots[i].parent ? g_slots[i].parent->max_sectors_per_xfer() : 1; } \
    static int p##i##_flush(void) { return g_slots[i].parent->flush(); }      \
    static int p##i##_trim(uint32_t l, uint32_t c) { return slot_trim(&g_slots[i], l, c); }

PART_THUNKS(0) PART_THUNKS(1) PART_THUNKS(2) PART_THUNKS(3)
PART_THUNKS(4) PART_THUNKS(5) PART_THUNKS(6) PART_THUNKS(7)

#define PART_OPS(i) { p##i##_count, p##i##_read, p##i##_write, p##i##_xfer, p##i##_flush, p##i##_trim }

static const struct {
    uint32_t (*count)(void);
    int (*read)(uint32_t, int, void *);
    int (*write)(uint32_t, int, const void *);
    int (*xfer)(void);
    int (*flush)(void);
    int (*trim)(uint32_t, uint32_t);
} g_thunks[PART_SLOTS] = {
    PART_OPS(0), PART_OPS(1), PART_OPS(2), PART_OPS(3),
    PART_OPS(4), PART_OPS(5), PART_OPS(6), PART_OPS(7),
};

int blk_part_release(const struct block_device *dev) {
    for (int i = 0; i < PART_SLOTS; i++) {
        if (!g_slots[i].used || &g_slots[i].dev != dev) continue;
        if (!blk_untrack(dev)) return 0;   // in use, or not named
        g_slots[i].used = 0;
        g_slots[i].parent = NULL;
        g_slots[i].base = g_slots[i].sectors = 0;
        g_slots[i].name[0] = '\0';
        return 1;
    }
    return 0;
}

const struct block_device *blk_part_create(const struct block_device *parent,
                                           uint32_t base_lba, uint32_t sectors,
                                           int index) {
    if (!parent) return NULL;

    // Re-pointing rather than nesting: the boot scan walks the entries
    // by creating each in turn, so the caller may well hand back a
    // partition it got from here. A partition of a partition is not a
    // thing this models, and silently building one would put a second
    // offset on every LBA.
    for (int i = 0; i < PART_SLOTS; i++) {
        if (parent == &g_slots[i].dev) {
            base_lba += g_slots[i].base;
            parent = g_slots[i].parent;
            break;
        }
    }
    if (!parent) return NULL;

    if (sectors == 0) {
        klog_write(KLOG_ERR "block: partition refused -- empty window\n");
        return NULL;
    }
    if ((uint64_t)base_lba + (uint64_t)sectors > (uint64_t)parent->sector_count()) {
        klog_printf(KLOG_ERR "block: partition refused -- LBA %u+%u past the end of %s (%u sectors)\n",
                    base_lba, sectors, parent->name, parent->sector_count());
        return NULL;
    }

    // THE SAME WINDOW IS THE SAME DEVICE. Without this the boot scan's
    // pass and a later `mount` of the same partition would produce two
    // structs describing one volume, and the mount table's "is this
    // device already mounted?" check -- which compares pointers -- would
    // answer no while the answer is plainly yes.
    int free_slot = -1;
    for (int i = 0; i < PART_SLOTS; i++) {
        if (g_slots[i].used && g_slots[i].parent == parent &&
            g_slots[i].base == base_lba && g_slots[i].sectors == sectors) {
            return &g_slots[i].dev;
        }
        if (!g_slots[i].used && free_slot < 0) free_slot = i;
    }
    if (free_slot < 0) {
        klog_write(KLOG_ERR "block: partition refused -- no free window slots\n");
        return NULL;
    }

    struct part_slot *s = &g_slots[free_slot];
    s->parent = parent;
    s->base = base_lba;
    s->sectors = sectors;
    s->used = 1;
    // `<disk>p<index>`, and the index is the PARTITION TABLE's, not a
    // count of how many slots are in use -- `root=ata0p3` has to mean
    // the third entry in the table, which is what a person reading
    // `parttable` will type. Naming by slot order made partition 3 of
    // this disk "ata0p1", because the two firmware partitions ahead of
    // it are skipped.
    //
    // The DISK's name comes from the block table rather than from
    // parent->name, which is the driver's stem ("ata") and not an
    // identity ("ata0"); the fallback keeps a partition of an
    // unregistered parent nameable rather than calling it "?p3".
    const char *pname = blk_device_name(parent);
    if (pname[0] == '?') pname = parent->name;
    k_snprintf(s->name, sizeof(s->name), "%sp%d", pname, index);

    s->dev.name = s->name;
    s->dev.sector_count = g_thunks[free_slot].count;
    s->dev.read_sectors = g_thunks[free_slot].read;
    s->dev.write_sectors = g_thunks[free_slot].write;
    s->dev.max_sectors_per_xfer = g_thunks[free_slot].xfer;

    // Every capability is INHERITED, both the bit and the pointer, so
    // blk_register_over()'s both-directions honesty check keeps holding:
    // a partition of a device with no flush must not claim one.
    s->dev.persistent = parent->persistent;
    s->dev.caps = parent->caps;
    s->dev.flush = (parent->caps & BLK_CAP_FLUSH) ? g_thunks[free_slot].flush : NULL;
    s->dev.trim  = (parent->caps & BLK_CAP_TRIM)  ? g_thunks[free_slot].trim  : NULL;

    // Into the block table even though nothing is being made active --
    // the table is what gives a device its NAME, and an unnamed device
    // cannot be mounted by name. /boot's partition arrives here and
    // never through blk_register().
    blk_track(&s->dev, parent, base_lba);
    return &s->dev;
}

const struct block_device *blk_part_parent(const struct block_device *dev,
                                           uint32_t *out_base) {
    for (int i = 0; i < PART_SLOTS; i++) {
        if (g_slots[i].used && dev == &g_slots[i].dev) {
            if (out_base) *out_base = g_slots[i].base;
            return g_slots[i].parent;
        }
    }
    return NULL;
}

int blk_part_register(const struct block_device *parent,
                      uint32_t base_lba, uint32_t sectors, int index) {
    const struct block_device *dev = blk_part_create(parent, base_lba, sectors, index);
    if (!dev) return 0;
    uint32_t base = base_lba;
    const struct block_device *real_parent = blk_part_parent(dev, &base);
    return blk_register_over(dev, real_parent ? real_parent : parent, base);
}
