// tolibc's <math.h>: the transcendentals, checked against an
// INDEPENDENT implementation.
//
// EVERY EXPECTED VALUE IN THIS FILE WAS GENERATED BY THE HOST'S PYTHON
// (which calls the platform libm), not by running toy-os and writing
// down what it said. That distinction is the whole point: a test whose
// expectations came from the code under test agrees with the code under
// test, including where both are wrong. The generator is a few lines
// and lives in this file's git history rather than in tools/, because
// re-running it is a once-per-function event.
//
// THE TOLERANCE IS RELATIVE, not absolute, because these functions
// span 1e-10 to 1e300 and an absolute bound would be meaningless at
// both ends. 1e-12 relative is roughly the last three or four decimal
// digits of a double -- well short of the sub-ulp accuracy glibc
// reaches with multi-precision fallback paths, and far more than a
// program drawing a circle can tell.
//
// pow() gets a LOOSER bound and says so: it compounds log's error with
// exp's, and y*log(x) magnifies whatever log got wrong by |y|.
//
// Prints one line per FAILURE, plus a count -- 81 "ok" lines say
// nothing a single summary does not.
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "rt/sys.h"

static int g_fail;
static int g_checked;

static void report(const char *name, double got, double want, double tol) {
    g_checked++;
    double err;
    if (want == 0.0) err = fabs(got);
    else             err = fabs((got - want) / want);
    if (err <= tol && !isnan(got)) return;
    g_fail++;
    printf("  FAIL %s: got %.17g, wanted %.17g (relative error %.3g)\n",
           name, got, want, err);
}

// The ordinary bound.
static void chk1(const char *n, double got, double want) { report(n, got, want, 1e-12); }
// atan2 near the axes returns values whose exactness depends on the
// quadrant logic rather than on a polynomial, but the same bound holds.
static void chk2(const char *n, double got, double want) { report(n, got, want, 1e-12); }
// pow's looser bound -- see the header.
static void chkp(const char *n, double got, double want) { report(n, got, want, 1e-11); }

int main(void) {
    printf("libm_test: the transcendentals, against independently computed values\n");

    chk1("sin", sin(0), 0);
    chk1("sin", sin(0.5), 0.47942553860420301);
    chk1("sin", sin(1), 0.8414709848078965);
    chk1("sin", sin(2), 0.90929742682568171);
    chk1("sin", sin(3), 0.14112000805986721);
    chk1("sin", sin(-1.5), -0.99749498660405445);
    chk1("sin", sin(100), -0.50636564110975879);
    chk1("sin", sin(1000000), -0.34999350217129294);
    chk1("cos", cos(0), 1);
    chk1("cos", cos(0.5), 0.87758256189037276);
    chk1("cos", cos(1), 0.54030230586813977);
    chk1("cos", cos(2), -0.41614683654714241);
    chk1("cos", cos(3), -0.98999249660044542);
    chk1("cos", cos(-1.5), 0.070737201667702906);
    chk1("cos", cos(100), 0.86231887228768389);
    chk1("cos", cos(1000000), 0.93675212753314474);
    chk1("tan", tan(0.5), 0.54630248984379048);
    chk1("tan", tan(1), 1.5574077246549023);
    chk1("tan", tan(-1), -1.5574077246549023);
    chk1("tan", tan(2), -2.1850398632615189);
    chk1("exp", exp(0), 1);
    chk1("exp", exp(1), 2.7182818284590451);
    chk1("exp", exp(-1), 0.36787944117144233);
    chk1("exp", exp(10), 22026.465794806718);
    chk1("exp", exp(-10), 4.5399929762484854e-05);
    chk1("exp", exp(700), 1.0142320547350045e+304);
    chk1("exp", exp(0.5), 1.6487212707001282);
    chk1("log", log(1), 0);
    chk1("log", log(2), 0.69314718055994529);
    chk1("log", log(10), 2.3025850929940459);
    chk1("log", log(0.5), -0.69314718055994529);
    chk1("log", log(10000000000), 23.025850929940457);
    chk1("log", log(1e-10), -23.025850929940457);
    chk1("log", log(2.7182818284590451), 1);
    chk1("atan", atan(0), 0);
    chk1("atan", atan(0.5), 0.46364760900080609);
    chk1("atan", atan(1), 0.78539816339744828);
    chk1("atan", atan(2), 1.1071487177940904);
    chk1("atan", atan(-3), -1.2490457723982544);
    chk1("atan", atan(100), 1.5607966601082315);
    chk1("asin", asin(0), 0);
    chk1("asin", asin(0.5), 0.52359877559829893);
    chk1("asin", asin(-0.5), -0.52359877559829893);
    chk1("asin", asin(0.90000000000000002), 1.1197695149986342);
    chk1("acos", acos(0), 1.5707963267948966);
    chk1("acos", acos(0.5), 1.0471975511965979);
    chk1("acos", acos(-0.5), 2.0943951023931957);
    chk1("acos", acos(0.90000000000000002), 0.45102681179626236);
    chk1("sinh", sinh(0), 0);
    chk1("sinh", sinh(1), 1.1752011936438014);
    chk1("sinh", sinh(-2), -3.6268604078470186);
    chk1("sinh", sinh(5), 74.203210577788752);
    chk1("cosh", cosh(0), 1);
    chk1("cosh", cosh(1), 1.5430806348152437);
    chk1("cosh", cosh(-2), 3.7621956910836314);
    chk1("cosh", cosh(5), 74.209948524787848);
    chk1("tanh", tanh(0), 0);
    chk1("tanh", tanh(0.5), 0.46211715726000974);
    chk1("tanh", tanh(-1), -0.76159415595576485);
    chk1("tanh", tanh(3), 0.99505475368673046);
    chk1("cbrt", cbrt(8), 2);
    chk1("cbrt", cbrt(27), 3.0000000000000004);
    chk1("cbrt", cbrt(-64), -4);
    chk1("cbrt", cbrt(2), 1.2599210498948734);
    chk1("log2", log2(1024), 10);
    chk1("log10", log10(1000), 3);
    chk1("exp2", exp2(10), 1024);
    chk2("atan2", atan2(1, 1), 0.78539816339744828);
    chk2("atan2", atan2(1, -1), 2.3561944901923448);
    chk2("atan2", atan2(-1, -1), -2.3561944901923448);
    chk2("atan2", atan2(-1, 1), -0.78539816339744828);
    chk2("atan2", atan2(0, -1), 3.1415926535897931);
    chk2("atan2", atan2(3, 4), 0.64350110879328437);
    chkp("pow", pow(2, 10), 1024);
    chkp("pow", pow(2, 0.5), 1.4142135623730951);
    chkp("pow", pow(10, -3), 0.001);
    chkp("pow", pow(2.5, 3.7000000000000002), 29.67413253642086);
    chkp("pow", pow(-2, 3), -8);
    chk1("hypot", hypot(3, 4), 5);
    chk1("hypot", hypot(9.9999999999999997e+199, 9.9999999999999997e+199), 1.414213562373095e+200);
    chk1("hypot", hypot(0, 5), 5);
    // --- the identities, which no table of values can fake ------------
    //
    // A function can match a list of sampled points and still be wrong
    // between them; an identity has to hold everywhere it is tested.
    for (int i = -30; i <= 30; i++) {
        double x = i * 0.37;
        report("sin^2+cos^2", sin(x) * sin(x) + cos(x) * cos(x), 1.0, 1e-12);
        report("exp(log)", (x > 0.1) ? log(exp(x)) : x, x, 1e-12);
        report("atan(tan)", (fabs(x) < 1.5) ? atan(tan(x)) : x, x, 1e-11);
    }
    // The squared identity is still worth having -- but only where it
    // is well conditioned, which is |x| small enough that cosh and
    // sinh are not yet nearly equal.
    for (int i = 1; i <= 8; i++) {
        double x = i * 0.25;
        report("cosh^2-sinh^2 (small x)",
               cosh(x) * cosh(x) - sinh(x) * sinh(x), 1.0, 1e-12);
    }
    for (int i = 1; i <= 40; i++) {
        double x = i * 0.25;
        report("log(exp)", exp(log(x)), x, 1e-12);
        report("cbrt^3", cbrt(x) * cbrt(x) * cbrt(x), x, 1e-11);
        // cosh + sinh == exp, NOT cosh^2 - sinh^2 and not
        // (cosh-sinh)(cosh+sinh). BOTH of those are ill-conditioned:
        // for large x, cosh and sinh are each about e^x/2, so their
        // difference cancels almost every digit and the check ends up
        // measuring the subtraction rather than the functions. The
        // first form reported errors up to 3e-8 and the second up to
        // 2.6e-8 against a cosh and sinh that were individually correct
        // to 1e-15 -- the test was wrong twice before it was right.
        //
        // Adding them cancels nothing, and it pins both against a third
        // function rather than only against each other.
        report("cosh+sinh == exp", cosh(x) + sinh(x), exp(x), 1e-12);
    }

    // --- the special cases -------------------------------------------
    //
    // Where libms actually disagree with each other, and where a
    // polynomial that is accurate in the middle says nothing.
    if (pow(2.0, 10.0) != 1024.0) { g_fail++; printf("  FAIL pow(2,10) is not exactly 1024\n"); }
    if (pow(0.0, 0.0) != 1.0) { g_fail++; printf("  FAIL pow(0,0) must be 1\n"); }
    if (pow(1.0, 1.0/0.0) != 1.0) { g_fail++; printf("  FAIL pow(1,inf) must be 1\n"); }
    if (!isnan(pow(-8.0, 0.5))) { g_fail++; printf("  FAIL a negative base with a fractional exponent must be NaN\n"); }
    if (pow(-2.0, 3.0) != -8.0) { g_fail++; printf("  FAIL a negative base with an integer exponent must work\n"); }
    if (!isinf(hypot(1.0/0.0, 0.0))) { g_fail++; printf("  FAIL hypot of infinity\n"); }
    if (log(0.0) != -1.0/0.0) { g_fail++; printf("  FAIL log(0) must be -inf\n"); }
    if (!isnan(log(-1.0))) { g_fail++; printf("  FAIL log of a negative must be NaN\n"); }
    if (!isnan(asin(2.0))) { g_fail++; printf("  FAIL asin out of domain must be NaN\n"); }
    if (tanh(100.0) != 1.0) { g_fail++; printf("  FAIL tanh saturates at 1\n"); }
    if (exp(-1000.0) != 0.0) { g_fail++; printf("  FAIL exp underflows to 0\n"); }
    if (!isinf(exp(1000.0))) { g_fail++; printf("  FAIL exp overflows to inf\n"); }
    double ip = 0;
    if (modf(-2.5, &ip) != -0.5 || ip != -2.0) { g_fail++; printf("  FAIL modf keeps the sign\n"); }
    g_checked += 13;

    printf("  %d values checked\n", g_checked);
    if (g_fail) printf("libm_test: %d FAILURES\n", g_fail);
    else        printf("libm_test: all checks passed\n");
    return g_fail;
}
