#ifndef VERSION_H
#define VERSION_H

// GENERATED by tools/gen_version.sh -- run automatically as the first
// step of `make all`/`make iso` (see the Makefile). Don't hand-edit
// this file, it gets overwritten on the very next build.
//
// TOYOS_VERSION is a plain build number (Windows-style, e.g. "22631"
// -- see CHANGELOG.md for the request this came from), shown by both
// the shell's `about` and the GUI About window. It's just whatever
// BUILD_NUMBER (repo root) currently holds -- this script doesn't
// increment it. BUILD_NUMBER only changes via tools/bump_build.sh, run
// once per real change (fix/feature/major -- see that script), not
// once per build, so the number reflects "how much has actually
// changed," not "how many times someone ran make."
#define TOYOS_VERSION "480"

#endif
