#!/usr/bin/env python3
"""Bake the kernel's function symbol table into the image, for panics.

A panic used to print a bare address. The kernel relocates itself to a
random base at boot, so that address meant nothing without the boot
log's relocation offset and a host-side addr2line -- i.e. a panic could
not be read on the machine it happened on. With this table the panic
names the function: `try_merge_next+0x2f`.

WHAT IT EMITS, and why it is shaped this way:

  a self-describing BLOB of literal bytes in its own `.ksyms` section

Two properties matter, and both are about relocations. The kernel
patches ~8,000 absolute references at boot from `.krelocs`
(tools/genrelocs.py); a table of `const char *` pointers or of
`&function` addresses would add one relocation PER SYMBOL to that list,
doubling it to no purpose. So the blob contains no pointers at all --
addresses are stored as LINK-TIME values in plain u32 literals, and
names live in a string table addressed by offset. Nothing in it needs
fixing up, and the resolver converts a running address to a link-time
one by subtracting the relocation delta it already knows.

Placement is the same trick `.krelocs` uses: the section sits after
everything it records, so adding it cannot move a single address in it.
`--verify` re-derives the table from the FINAL image and fails the build
if that ever stops being true.

    python3 tools/gen_syms.py build/kernel.pass1.elf --out-c build/ksyms.c
    python3 tools/gen_syms.py build/kernel.pass2.elf --verify build/ksyms.c
"""

import argparse
import re
import subprocess
import sys

KSYMS_MAGIC = 0x534D5953  # "SYMS"


def collect(elf):
    """Function symbols in the image, sorted by address.

    `nm` rather than readelf because the 't'/'T' type letters are exactly
    the filter wanted: text symbols, local and global alike. A local
    static helper is often precisely the frame a panic lands in, so
    dropping locals would lose the most useful names.
    """
    out = subprocess.run(["nm", "-n", elf], capture_output=True, text=True,
                          check=True).stdout
    syms = []
    for line in out.splitlines():
        m = re.match(r"^([0-9a-fA-F]+)\s+([tTwW])\s+(\S+)$", line)
        if not m:
            continue
        addr = int(m.group(1), 16)
        name = m.group(3)
        if addr == 0:
            continue
        # Compiler-generated cold/part clones share a prefix with their
        # parent and only add noise to a backtrace.
        name = name.split(".part.")[0].split(".cold")[0].split(".constprop")[0]
        if syms and syms[-1][0] == addr:
            continue  # aliases at one address -- keep the first
        syms.append((addr, name))
    return syms


def build_blob(syms):
    """magic, count, strings-offset, then the entries, then the strings."""
    strings = bytearray()
    offsets = []
    seen = {}
    for _, name in syms:
        if name in seen:
            offsets.append(seen[name])
            continue
        seen[name] = len(strings)
        offsets.append(len(strings))
        strings += name.encode("utf-8") + b"\0"

    header = 12
    entries = len(syms) * 8
    blob = bytearray()
    blob += KSYMS_MAGIC.to_bytes(4, "little")
    blob += len(syms).to_bytes(4, "little")
    blob += (header + entries).to_bytes(4, "little")  # where strings start
    for (addr, _), off in zip(syms, offsets):
        if addr > 0xFFFFFFFF:
            sys.exit("gen_syms: a symbol sits above 4 GiB -- the table "
                      "stores link-time addresses as u32 (see this file)")
        blob += addr.to_bytes(4, "little")
        blob += off.to_bytes(4, "little")
    blob += strings
    return bytes(blob)


def emit_c(blob, path):
    rows = []
    for i in range(0, len(blob), 16):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in blob[i:i + 16]))
    body = "\n".join(rows)
    with open(path, "w") as f:
        f.write(f"""// GENERATED by tools/gen_syms.py -- do not edit.
//
// The kernel's function symbol table, as a relocation-free blob in its
// own section. See that tool for the format and why it contains no
// pointers. kernel/core/ksyms.c reads it; a panic prints names from it.
__attribute__((section(".ksyms"), used))
const unsigned char ksyms_blob[] = {{
{body}
}};
""")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("elf")
    ap.add_argument("--out-c")
    ap.add_argument("--verify", metavar="C_FILE")
    args = ap.parse_args()

    syms = collect(args.elf)
    if not syms:
        sys.exit("gen_syms: no text symbols found -- is this a linked kernel?")
    blob = build_blob(syms)

    if args.verify:
        want = open(args.verify).read()
        cur = f"const unsigned char ksyms_blob[] = {{"
        if cur not in want:
            sys.exit(f"gen_syms: {args.verify} is not a generated table")
        # Compare the byte count only: the table records link-time
        # addresses of code that sits BEFORE it, so a size match means
        # the same symbols at the same places. A real mismatch here means
        # .ksyms moved above something it records -- the same failure
        # genrelocs.py's --verify exists to catch.
        have = len(re.findall(r"0x[0-9a-f]{2},", want))
        if have != len(blob):
            sys.exit(f"gen_syms: STALE -- {args.verify} has {have} bytes, "
                      f"the final image needs {len(blob)}. The .ksyms section "
                      f"has probably moved above code it records; see "
                      f"linker.ld's placement comment.")
        print(f"gen_syms: OK -- {len(syms)} symbols, {len(blob)} bytes")
        return 0

    if not args.out_c:
        sys.exit("gen_syms: need --out-c or --verify")
    emit_c(blob, args.out_c)
    print(f"gen_syms: {len(syms)} symbols, {len(blob)} bytes -> {args.out_c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
