#!/usr/bin/env python3
"""tools/gen_decisions_index.py -- regenerate docs/decisions.md from docs/decisions/.

WHY IT IS GENERATED
-------------------
`docs/decisions.md` used to carry its index by hand, with a line in the
file asking whoever added an entry to remember to add a link. That is
the same shape as every convention this repo has since deleted: a file
made responsible for staying true, kept true by someone remembering.
See CLAUDE.md's "prefer facts that cannot go stale".

So the index is derived. Add an entry to the right file under
`docs/decisions/`, run this, and the index is correct by construction.
`tools/check_docs.py` fails the build if the committed index does not
match what this would produce, which is what makes "run this" a rule
rather than a hope.

WHAT IT DOES NOT TOUCH
----------------------
The preamble above the index -- the part that says what the file is for
and what the bar for an entry is. That is prose, it is not derived from
anything, and regenerating it would mean this script owned an argument
it did not make. It is read from the current `docs/decisions.md` and
passed through unchanged; the marker below is the boundary.
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(REPO, "docs", "decisions.md")
DIR = os.path.join(REPO, "docs", "decisions")
MARKER = "## Index"

# Display order, and the heading each file appears under. Order is
# editorial -- foundations first, then what sits on them -- so it is
# stated here rather than derived from a directory listing.
ORDER = [
    ("kernel.md",   "Kernel, memory & processes"),
    ("storage.md",  "Filesystem & storage"),
    ("drivers.md",  "Drivers & hardware"),
    ("gui.md",      "GUI: window manager, compositor & widgets"),
    ("shell.md",    "Shell, apps & console"),
    ("build.md",    "Build, versioning & project docs"),
    ("workflow.md", "Session workflow & environment"),
]


def anchor(title):
    """GitHub's heading-anchor slug: lowercase, punctuation dropped,
    spaces to hyphens. Kept in one place because a wrong slug produces a
    link that looks right and lands nowhere."""
    a = title.lower()
    a = re.sub(r"[^\w\s-]", "", a)
    return re.sub(r"\s+", "-", a.strip())


def entries(path):
    """Every `## ` heading in a decisions file, in file order."""
    with open(path) as f:
        text = f.read()
    return [m.group(1).strip() for m in re.finditer(r"^## (.+)$", text, re.M)]


def build():
    out = [MARKER, ""]
    total = 0
    for fn, heading in ORDER:
        path = os.path.join(DIR, fn)
        if not os.path.exists(path):
            continue
        titles = entries(path)
        total += len(titles)
        out.append(f"**{heading}** -- [`decisions/{fn}`](decisions/{fn})"
                   f" ({len(titles)} entries)")
        out.append("")
        for t in titles:
            out.append(f"- [{t}](decisions/{fn}#{anchor(t)})")
        out.append("")
    out.append(f"<!-- {total} entries. Generated by tools/gen_decisions_index.py"
               f" -- do not edit below the marker by hand. -->")
    return "\n".join(out) + "\n"


def current_preamble():
    with open(INDEX) as f:
        text = f.read()
    i = text.find(MARKER)
    if i < 0:
        raise SystemExit(f"gen_decisions_index: no '{MARKER}' marker in {INDEX}")
    return text[:i]


def main():
    want = current_preamble() + build()
    check = "--check" in sys.argv
    with open(INDEX) as f:
        have = f.read()
    if have == want:
        print("gen_decisions_index: up to date")
        return 0
    if check:
        print("gen_decisions_index: docs/decisions.md is STALE -- run "
              "tools/gen_decisions_index.py")
        return 1
    with open(INDEX, "w") as f:
        f.write(want)
    print(f"gen_decisions_index: rewrote {os.path.relpath(INDEX, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
