#!/bin/sh
# Regenerates kernel/include/version.h from VERSION (repo root, plain
# text, one line -- a semver-ish string like "0.1.0-dev" or "0.1.0"),
# run automatically as the first step of `make all`/`make iso` (see
# the Makefile). Not meant to be edited by hand -- kernel/include/
# version.h itself says so too -- but harmless to run directly if you
# just want to see what it'd produce.
#
# This script does NOT change VERSION itself -- it just embeds
# whatever VERSION currently holds. Changing VERSION is a separate,
# deliberate step (tools/set_version.sh), run only when you're
# starting a new round of dev work or cutting a real release -- not on
# every build, and not on every change either (unlike the retired
# per-change build-number scheme this replaced, see CHANGELOG.md and
# docs/decisions.md).
#
# Idempotent by design (only overwrites version.h if the content
# actually changed): this runs on literally every `make all`/`make
# iso`, and kernel/include/kapi.h includes version.h, so with the
# Makefile's -MMD/-MP header dependency tracking (see its top comment),
# an unconditional overwrite here would bump version.h's mtime on
# every single build and make every file that (transitively) includes
# kapi.h -- which is nearly everything -- look "out of date" and
# rebuild every time, defeating the entire point of that tracking. By
# only touching the file when VERSION actually changed, a build right
# after `set_version.sh` correctly recompiles everything that depends
# on version.h (same as before), but every other build in between
# leaves its mtime alone, same as any other untouched header.
set -e
cd "$(dirname "$0")/.."

VERSION_FILE="VERSION"
VERSION="0.0.0-dev"
if [ -f "$VERSION_FILE" ]; then
    VERSION=$(cat "$VERSION_FILE")
fi

OUT="kernel/include/version.h"
TMP="$OUT.tmp.$$"

cat > "$TMP" << EOF
#ifndef VERSION_H
#define VERSION_H

// GENERATED by tools/gen_version.sh -- run automatically as the first
// step of \`make all\`/\`make iso\` (see the Makefile). Don't hand-edit
// this file, it gets overwritten on the very next build.
//
// TOYOS_VERSION is a semver-ish string ("0.1.0-dev" while in
// development, "0.1.0" once released -- see VERSION at the repo root
// and tools/set_version.sh), shown by both the shell's \`about\` and
// the GUI About window. It's just whatever VERSION currently holds --
// this script doesn't change it. See docs/decisions.md for why this
// replaced the earlier per-change build-number scheme.
#define TOYOS_VERSION "$VERSION"

#endif
EOF

if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    rm -f "$TMP"
    echo "version: $VERSION (unchanged)"
else
    mv "$TMP" "$OUT"
    echo "version: $VERSION"
fi
