#!/bin/sh
# Regenerates kernel/include/version.h from BUILD_NUMBER (repo root,
# plain text, one line -- just the integer), run automatically as the
# first step of `make all`/`make iso` (see the Makefile). Not meant to
# be edited by hand -- kernel/include/version.h itself says so too --
# but harmless to run directly if you just want to see what it'd
# produce.
#
# Unlike the retired date-plus-build-counter scheme this replaced (see
# CHANGELOG.md), this script does NOT increment anything -- it just
# embeds whatever BUILD_NUMBER currently holds. Bumping BUILD_NUMBER
# itself is a separate, deliberate step (tools/bump_build.sh) run once
# per real change, not once per build -- see that script's top comment
# for why "every build" and "every change" are different things here.
set -e
cd "$(dirname "$0")/.."

COUNTER_FILE="BUILD_NUMBER"
BUILD_NUMBER=0
if [ -f "$COUNTER_FILE" ]; then
    BUILD_NUMBER=$(cat "$COUNTER_FILE")
fi

cat > kernel/include/version.h << EOF
#ifndef VERSION_H
#define VERSION_H

// GENERATED by tools/gen_version.sh -- run automatically as the first
// step of \`make all\`/\`make iso\` (see the Makefile). Don't hand-edit
// this file, it gets overwritten on the very next build.
//
// TOYOS_VERSION is a plain build number (Windows-style, e.g. "22631"
// -- see CHANGELOG.md for the request this came from), shown by both
// the shell's \`about\` and the GUI About window. It's just whatever
// BUILD_NUMBER (repo root) currently holds -- this script doesn't
// increment it. BUILD_NUMBER only changes via tools/bump_build.sh, run
// once per real change (fix/feature/major -- see that script), not
// once per build, so the number reflects "how much has actually
// changed," not "how many times someone ran make."
#define TOYOS_VERSION "$BUILD_NUMBER"

#endif
EOF

echo "version: build $BUILD_NUMBER"
