#!/usr/bin/env python3
"""Generate docs/toolkit.md: every ring-3 toolkit header, one line each.

WHY THIS EXISTS. `userland/lib/` and `userland/ui/` had no index, so a
session writing an app could not find what already existed: Crash Reports
hand-rolled a fourth `.desktop` reader while `uconf` and Task Manager's
loader sat one directory away. The headers already say what they are --
their top comment is the best one-line description in the tree -- so the
index is DERIVED from them and cannot go stale: `--check` (run by
`tools/check_docs.py`) fails when docs/toolkit.md differs from what this
would write, and a header with no top comment fails it too.

THE ONE-LINER is the first sentence of a header's first comment
paragraph, markdown emphasis removed. An `_internal.h`/`_int.h` header is
a module's private seam (CLAUDE.md, "split by concern") and is listed
separately without a description.

    python3 tools/gen_toolkit_index.py          # write docs/toolkit.md
    python3 tools/gen_toolkit_index.py --check  # exit 1 if stale
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs", "toolkit.md")
DIRS = [
    ("userland/lib", "The library: files, text, config, settings, media, IPC"),
    ("userland/ui", "Widgets, the theme and the app framework (`uapp`)"),
]
MAX_LINE = 200


def is_internal(name):
    return name.endswith("_internal.h") or name.endswith("_int.h")


def first_sentence(path):
    """The first sentence of the header's first comment paragraph, or None."""
    para = []
    started = False
    with open(path, encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not started:
                if not line or line.startswith("#"):
                    continue
                if not (line.startswith("//") or line.startswith("/*")):
                    return None          # code before any comment
                started = True
            if line.startswith("//"):
                text = line[2:].strip()
            elif line.startswith("/*") or line.startswith("*"):
                text = line.lstrip("/*").rstrip("*/").strip()
            else:
                break
            if not text:
                if para:
                    break                # end of the first paragraph
                continue
            para.append(text)
            if line.endswith("*/"):
                break
    if not para:
        return None
    text = " ".join(para)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    m = re.search(r"(.+?[.!?])(\s|$)", text)
    s = (m.group(1) if m else text).strip()
    if len(s) > MAX_LINE:
        s = s[:MAX_LINE - 3].rstrip() + "..."
    return s.replace("|", "\\|")


def build():
    out = [
        "# The ring-3 toolkit, by header",
        "",
        "**GENERATED by `tools/gen_toolkit_index.py` from each header's top "
        "comment -- do not edit here; change the header and rerun.** "
        "`tools/check_docs.py` fails when this is stale.",
        "",
        "**Check this before writing a helper or a widget inside an app.** "
        "Anything generic by nature -- its job names no app's data -- "
        "belongs here from its first caller (CLAUDE.md). The kernel's own "
        "toolkit (`kernel/lib/`, reached through `kapi.h`) is listed in "
        "CLAUDE.md; the widget catalogue with when-to-use guidance is "
        "`docs/gui-guidelines.md`.",
    ]
    missing = []
    for rel, title in DIRS:
        d = os.path.join(REPO, rel)
        headers = sorted(f for f in os.listdir(d) if f.endswith(".h"))
        out += ["", f"## `{rel}/` -- {title}", "",
                "| Header | What it is |", "|---|---|"]
        internal = []
        for h in headers:
            if is_internal(h):
                internal.append(h)
                continue
            s = first_sentence(os.path.join(d, h))
            if s is None:
                missing.append(f"{rel}/{h}")
                s = "(no top comment)"
            out.append(f"| `{h}` | {s} |")
        if internal:
            out += ["", "Private seams of a split module, not for apps: " +
                    ", ".join(f"`{h}`" for h in internal) + "."]
    return "\n".join(out) + "\n", missing


def main():
    text, missing = build()
    if "--check" in sys.argv[1:]:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        bad = cur != text
        for m in missing:
            print(f"gen_toolkit_index: {m} has no top comment saying what it is")
        if bad:
            print("gen_toolkit_index: docs/toolkit.md is stale -- run "
                  "tools/gen_toolkit_index.py")
        return 1 if bad or missing else 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("gen_toolkit_index: wrote docs/toolkit.md"
          + (f" ({len(missing)} header(s) with no top comment)" if missing else ""))
    for m in missing:
        print(f"  {m}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
