#!/bin/sh
# Writes the kernel's build-time timer configuration as a header:
#
#     sh tools/gen_kconfig.sh <hz> <idle|periodic> <0|1> <out.h>
#
# The values come from build.conf's `option hz/tick/highres` (through
# build/conf.mk) or from the make command line. Run at Makefile PARSE
# time, like gen_version.sh, and IDEMPOTENT for the same reason: the
# header is only rewritten when a value changed, so -MMD rebuilds the
# files that include it after `make HZ=250` and nothing on a plain
# rebuild. A value outside the known set exits non-zero and the Makefile
# stops -- a typo must not become a kernel ticking at a rate nobody chose.
set -e
hz=$1 tick=$2 highres=$3 out=$4
case "$hz" in 100|250|300|500|1000) ;; *)
    echo "gen_kconfig: HZ=$hz -- want 100, 250, 300, 500 or 1000" >&2; exit 1;; esac
case "$tick" in idle) idle=1;; periodic) idle=0;; *)
    echo "gen_kconfig: TICK=$tick -- want idle or periodic" >&2; exit 1;; esac
case "$highres" in 0|1) ;; *)
    echo "gen_kconfig: HIGHRES=$highres -- want 0 or 1" >&2; exit 1;; esac

mkdir -p "$(dirname "$out")"
tmp="$out.tmp"
cat > "$tmp" <<HDR
// GENERATED by tools/gen_kconfig.sh from build.conf -- do not edit.
#ifndef KCONFIG_H
#define KCONFIG_H
#define CONFIG_HZ $hz
#define CONFIG_TICK_IDLE $idle
#define CONFIG_HIGHRES $highres
#endif
HDR
if cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv "$tmp" "$out"; fi
