#!/usr/bin/env python3
"""Generate the cursor themes into data/cursors/<theme>/.

The Makefile stages data/cursors/ to /usr/share/cursors/ on the image.
A shape's file is a small key=value descriptor (shape, width, height,
hotspot) and then ONE of two bodies -- Xcursor's split between a mask
cursor and an ARGB one:

  * MASKS (default, bold): two coverage grids, outline and fill, which
    the compositor colours at draw time -- one shape set then serves a
    light theme and a dark one.
  * an IMAGE (graphite, accent, amber, aurora): `image=` names a
    straight-alpha QOI beside the descriptor, and `image2=`/`image3=`
    the same shape rendered natively at 2x and 3x for the size setting.
    Its colours are its own; the compositor only composites it.

Why a generator rather than hand-written files: the default theme's
arrow already exists as two anti-aliased C arrays in userland/wm/wm_render.c
and the three resize shapes already exist as procedural loops in the
same file. Re-typing either by hand is exactly the kind of transcription
this repo has been bitten by, so the arrow is EXTRACTED from the source
and the resize shapes are a port of the same loops. Run this after
changing either, and the shipped theme cannot drift from the built-in
fallback.

It is also the authoring tool: a mask theme is a function here that
returns {shape name: Shape}, an image theme a row of IMAGE_THEMES (fill,
rim and busy-ring colours over the shared supersampled geometry).
Pillow encodes the QOI files, as tools/gen_icons.py's do.

    python3 tools/gen_cursors.py            # write the themes
    python3 tools/gen_cursors.py --check    # fail if they are stale (CI)
"""

import argparse
import io
import math
import os
import re
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WM_RENDER = os.path.join(REPO, "userland", "wm", "wm_render.c")
OUT_ROOT = os.path.join(REPO, "data", "cursors")

# One hex digit per pixel, so a 13-wide shape is 13 characters wide and
# a person can see the shape in the file. 16 levels is well past what a
# cursor needs and keeps the grid readable; '.' is a synonym for 0 so
# the drawn shape stands out from its background.
RAMP = "0123456789abcdef"


def to_char(alpha):
    if alpha <= 0:
        return "."
    return RAMP[min(15, (alpha * 15 + 127) // 255)]


class Shape:
    def __init__(self, w, h, hot=(0, 0)):
        self.w, self.h, self.hot = w, h, hot
        self.outline = [[0] * w for _ in range(h)]
        self.fill = [[0] * w for _ in range(h)]

    def text(self, name):
        lines = [
            "# toy-os cursor shape -- generated by tools/gen_cursors.py",
            "# Coverage per pixel, one hex digit (0-f); '.' is 0.",
            "# The compositor supplies the colours; these are masks.",
            f"shape={name}",
            f"width={self.w}",
            f"height={self.h}",
            f"hotspot={self.hot[0]},{self.hot[1]}",
            "outline=",
        ]
        lines += ["".join(to_char(a) for a in row) for row in self.outline]
        lines.append("fill=")
        lines += ["".join(to_char(a) for a in row) for row in self.fill]
        return "\n".join(lines) + "\n"


def extract_arrow():
    """The default arrow, taken from wm_render.c's own baked masks."""
    src = open(WM_RENDER).read()

    def grid(sym):
        m = re.search(
            r"cursor_%s_alpha\[CURSOR_SPRITE_H\]\[CURSOR_SPRITE_W\]\s*=\s*\{(.*?)\n\};" % sym,
            src, re.S)
        if not m:
            sys.exit(f"gen_cursors: could not find cursor_{sym}_alpha in {WM_RENDER}")
        rows = re.findall(r"\{([0-9,\s]+)\}", m.group(1))
        return [[int(v) for v in r.split(",")] for r in rows]

    out, fil = grid("outline"), grid("fill")
    h, w = len(out), len(out[0])
    s = Shape(w, h, (0, 0))  # the arrow's tip is its top-left pixel
    s.outline, s.fill = out, fil
    return s


# The resize arrow, ONE profile for all three directions. See
# wm_render.c's draw_resize_cursor(), which is the same arithmetic in C
# -- change both.
#
# Rasterised ANALYTICALLY rather than stepped along the axis: a stepped
# diagonal sets only pixels whose x+y is even, so the corner cursor came
# out a CHECKERBOARD, which is why it read as bigger and different from
# the edge ones. Scanning every pixel and asking how far along the arrow
# (u) and how far across it (v) it lies is solid in any direction, and
# makes the three the same arrow rotated rather than three constructions.
RZ_S = 256          # fixed point: 1 px
RZ_LEN = 19 * RZ_S  # tip to tip
RZ_HEAD = 5 * RZ_S  # of which each arrowhead
RZ_HW = 1152        # 4.5 px -- the head's half-width at its base
RZ_SW = 384         # 1.5 px -- the shaft's
RZ_DIAG = 181       # 256 / sqrt(2), so a diagonal arrow is 19 px long too


def rz_halfwidth(u):
    """Half the arrow's width at `u` along it, or -1 past either end."""
    if u < 0 or u > RZ_LEN:
        return -1
    if u < RZ_HEAD:
        return RZ_HW * u // RZ_HEAD
    if u > RZ_LEN - RZ_HEAD:
        return RZ_HW * (RZ_LEN - u) // RZ_HEAD
    return RZ_SW


def resize_shape(kind):
    """A double-headed arrow: outlined, 3 px shaft, 19 px tip to tip."""
    n = 34
    c = n // 2
    fill = [[0] * n for _ in range(n)]
    for y in range(n):
        for x in range(n):
            dx, dy = x - c, y - c
            if kind == "h":
                u, v = dx * RZ_S + RZ_LEN // 2, dy * RZ_S
            elif kind == "v":
                u, v = dy * RZ_S + RZ_LEN // 2, dx * RZ_S
            elif kind == "diag":
                u, v = (dx + dy) * RZ_DIAG + RZ_LEN // 2, (dx - dy) * RZ_DIAG
            else:  # "diag2" -- the / axis, the \ one mirrored in y
                u, v = (dx - dy) * RZ_DIAG + RZ_LEN // 2, (dx + dy) * RZ_DIAG
            hw = rz_halfwidth(u)
            if hw >= 0 and abs(v) <= hw + RZ_S // 2:
                fill[y][x] = 1

    xs = [x for y in range(n) for x in range(n) if fill[y][x]]
    ys = [y for y in range(n) for x in range(n) if fill[y][x]]
    x0, x1 = min(xs) - 1, max(xs) + 1
    y0, y1 = min(ys) - 1, max(ys) + 1
    w, h = x1 - x0 + 1, y1 - y0 + 1

    s = Shape(w, h, (c - x0, c - y0))   # the hotspot is the arrow's centre
    for y in range(h):
        for x in range(w):
            if fill[y + y0][x + x0]:
                s.fill[y][x] = 255
    # Outlined all round, so it reads against a light window border --
    # the previous shape's middle was bare white and vanished there.
    for y in range(h):
        for x in range(w):
            if s.fill[y][x]:
                continue
            if any(0 <= y + dy < h and 0 <= x + dx < w and s.fill[y + dy][x + dx]
                   for dy in (-1, 0, 1) for dx in (-1, 0, 1)):
                s.outline[y][x] = 255
    return s


def ibeam():
    """A text cursor: a vertical bar with serifs, outlined for contrast."""
    s = Shape(7, 17, (3, 8))
    for y in range(1, 16):
        s.fill[y][3] = 255
    for x in range(1, 6):           # serifs, top and bottom
        s.fill[1][x] = 255
        s.fill[15][x] = 255
    # Outline every fill pixel's neighbours that are not themselves fill,
    # so the bar stays visible over text of any colour.
    for y in range(s.h):
        for x in range(s.w):
            if s.fill[y][x]:
                continue
            near = any(0 <= y + dy < s.h and 0 <= x + dx < s.w and s.fill[y + dy][x + dx]
                       for dy in (-1, 0, 1) for dx in (-1, 0, 1))
            if near:
                s.outline[y][x] = 255
    return s


def hourglass():
    """A wait cursor: an hourglass, drawn as two facing wedges."""
    s = Shape(11, 15, (5, 7))
    for y in range(15):
        if y in (0, 14):
            for x in range(1, 10):
                s.outline[y][x] = 255
            continue
        # Half-width shrinks to the waist at y=7 and grows again.
        half = 4 - abs(7 - y) * 4 // 7
        for x in range(5 - half, 5 + half + 1):
            s.fill[y][x] = 255
        if 5 - half - 1 >= 0:
            s.outline[y][5 - half - 1] = 255
        if 5 + half + 1 < s.w:
            s.outline[y][5 + half + 1] = 255
    return s


# --- the shared geometry: the image themes, and the new mask shapes ----
#
# Each draws a coverage mask with PIL at `s` canvas pixels per 1x pixel
# (supersampling times the target scale), on a canvas of GEOM's 1x size
# that leaves room for the rim and the shadow. Returns the hotspot at 1x.

SS = 8  # supersampling: drawn at 8x the target, box-reduced to it


def g_arrow(d, s):
    pts = [(0, 0), (0, 15.5), (3.9, 12.0), (6.6, 17.8), (9.0, 16.7), (6.4, 11.1), (11.2, 11.1)]
    d.polygon([((x + 2) * s, (y + 2) * s) for x, y in pts], fill=255)
    return (2, 2)


def g_ibeam(d, s):
    cx, top, bot = 5.5, 2.0, 19.0
    d.rounded_rectangle([(cx - 0.9) * s, top * s, (cx + 0.9) * s, bot * s], radius=0.6 * s, fill=255)
    for y in (top, bot - 1.8):
        d.rounded_rectangle([(cx - 3.4) * s, y * s, (cx + 3.4) * s, (y + 1.8) * s],
                            radius=0.9 * s, fill=255)
    return (5, 10)


def g_double_arrow(d, s, angle, cx=12.0, cy=12.0, L=18.0, H=6.0, hw=4.8, sw=1.3):
    half = L / 2
    pts = [(-half, 0), (-half + H, -hw), (-half + H, -sw), (half - H, -sw), (half - H, -hw),
           (half, 0), (half - H, hw), (half - H, sw), (-half + H, sw), (-half + H, hw)]
    ca, sa = math.cos(angle), math.sin(angle)
    d.polygon([((cx + x * ca - y * sa) * s, (cy + x * sa + y * ca) * s) for x, y in pts], fill=255)
    return (12, 12)


RING = (11.0, 11.0, 8.0)  # the busy ring's centre and outer radius, 1x


def g_ring(d, s, w=3.4):
    cx, cy, r = RING
    d.ellipse([(cx - r) * s, (cy - r) * s, (cx + r) * s, (cy + r) * s], fill=255)
    d.ellipse([(cx - r + w) * s, (cy - r + w) * s, (cx + r - w) * s, (cy + r - w) * s], fill=0)
    return (11, 11)


def g_hand(d, s):
    """A pointing hand: index finger up, three folded knuckles, a thumb."""
    ox, oy = 3.0, 1.5

    def R(x0, y0, x1, y1, r):
        d.rounded_rectangle([(ox + x0) * s, (oy + y0) * s, (ox + x1) * s, (oy + y1) * s],
                            radius=r * s, fill=255)
    R(4.6, 0.0, 7.8, 12.0, 1.6)     # index
    R(7.4, 6.4, 10.4, 12.6, 1.5)    # middle knuckle
    R(10.0, 7.2, 13.0, 13.2, 1.5)   # ring knuckle
    R(12.6, 8.2, 15.4, 13.8, 1.4)   # little knuckle
    R(4.6, 9.6, 15.4, 20.0, 3.2)    # palm
    d.polygon([((ox + x) * s, (oy + y) * s) for x, y in
               [(5.2, 11.2), (2.4, 8.4), (0.9, 8.2), (0.2, 9.6), (3.4, 15.8), (5.6, 17.2)]],
              fill=255)             # thumb
    return (9, 2)                   # the index fingertip


def g_move(d, s, c=12.0):
    for a in (0, math.pi / 2):
        g_double_arrow(d, s, a, cx=c, cy=c, L=20.0, H=5.5, hw=4.2, sw=1.2)
    return (12, 12)


def g_not_allowed(d, s, cx=11.0, cy=11.0, r=8.0, w=2.6):
    d.ellipse([(cx - r) * s, (cy - r) * s, (cx + r) * s, (cy + r) * s], fill=255)
    d.ellipse([(cx - r + w) * s, (cy - r + w) * s, (cx + r - w) * s, (cy + r - w) * s], fill=0)
    ca = sa = math.cos(math.pi / 4)
    hw, half = w / 2, r - w / 2
    pts = [(-half, -hw), (half, -hw), (half, hw), (-half, hw)]
    d.polygon([((cx + x * ca - y * sa) * s, (cy + x * sa + y * ca) * s) for x, y in pts], fill=255)
    return (11, 11)


GEOM = {
    "arrow": ((16, 23), g_arrow),
    "text": ((11, 22), g_ibeam),
    "wait": ((23, 23), g_ring),
    "resize-h": ((25, 25), lambda d, s: g_double_arrow(d, s, 0)),
    "resize-v": ((25, 25), lambda d, s: g_double_arrow(d, s, math.pi / 2)),
    "resize-diag": ((25, 25), lambda d, s: g_double_arrow(d, s, math.pi / 4, L=19.5)),
    "resize-diag2": ((25, 25), lambda d, s: g_double_arrow(d, s, -math.pi / 4, L=19.5)),
    "hand": ((22, 25), g_hand),
    "move": ((25, 25), g_move),
    "not-allowed": ((23, 23), g_not_allowed),
}


def dilate(m, px):
    """Grow a mask by `px` canvas pixels, rounded at the corners.

    Repeated 3x3 max rather than one wide kernel: a rank filter's cost
    is quadratic in its size, and a 3x shape's rim is a 60-pixel kernel.
    """
    for _ in range(max(1, int(round(px)))):
        m = m.filter(ImageFilter.MaxFilter(3))
    return m.filter(ImageFilter.GaussianBlur(px * 0.28)).point(lambda v: 255 if v > 110 else 0)


def geom_mask(name, k):
    """(supersampled mask, its canvas size at k, the 1x hotspot)."""
    (w, h), fn = GEOM[name]
    s = SS * k
    m = Image.new("L", (w * s, h * s), 0)
    hot = fn(ImageDraw.Draw(m), s)
    return m, (w * k, h * k), hot


def paint(mask, spec, size):
    """`mask` as alpha over a flat, vertical or diagonal fill of `size`."""
    w, h = size
    im = Image.new("RGB", size)
    px = im.load()
    for y in range(h):
        for x in range(w):
            if spec[0] == "flat":
                c = spec[1]
            else:
                t = y / max(1, h - 1) if spec[0] == "v" else (x + y) / max(1, w + h - 2)
                c = tuple(int(spec[1][i] + (spec[2][i] - spec[1][i]) * t) for i in range(3))
            px[x, y] = c
    im.putalpha(mask)
    return im


# An image theme: the fill, the rim, and the busy ring's track and
# 120-degree arc. Colours are the theme's OWN -- nothing repaints them.
WHITE = ("flat", (255, 255, 255))
IMAGE_THEMES = {
    # Breeze/Adwaita/macOS: dark, white rim; the accent only in the ring.
    "graphite": dict(fill=("flat", (30, 30, 34)), rim=WHITE,
                     track=("flat", (70, 70, 78)), arc=("diag", (110, 160, 230), (70, 110, 160))),
    # Windows 11's pointer colour, in the theme's accent blue.
    "accent": dict(fill=("v", (104, 150, 214), (60, 100, 156)), rim=WHITE, arc=WHITE),
    # Bibata Modern Amber: a warm gradient, a dark rim.
    "amber": dict(fill=("v", (255, 200, 90), (236, 128, 0)), rim=("flat", (40, 26, 8)),
                  arc=("flat", (40, 26, 8))),
    # Teal to violet, from the default wallpaper.
    "aurora": dict(fill=("diag", (40, 200, 180), (120, 90, 240)), rim=WHITE,
                   arc=("diag", (255, 255, 255), (220, 230, 255))),
}
RIM_PX = 1.25     # the rim's width, at 1x
SHADOW_A = 0.38   # the drop shadow's peak opacity
SCALES = (1, 2, 3)


def render_image(theme, name, k):
    """One shape of an image theme at scale k, rendered natively."""
    spec = IMAGE_THEMES[theme]
    m, size, hot = geom_mask(name, k)
    s = SS * k
    rim = dilate(m, RIM_PX * s)
    shadow = ImageChops.offset(rim, int(0.8 * s), int(1.4 * s))
    shadow = shadow.filter(ImageFilter.GaussianBlur(s * 1.3)).point(lambda v: int(v * SHADOW_A))
    down = lambda im: im.resize(size, Image.LANCZOS)  # noqa: E731
    out = Image.new("RGBA", size, (0, 0, 0, 0))
    out.alpha_composite(Image.merge("RGBA", (*[Image.new("L", size, 0)] * 3, down(shadow))))
    out.alpha_composite(paint(down(rim), spec["rim"], size))
    out.alpha_composite(paint(down(m), spec.get("track", spec["fill"]) if name == "wait"
                              else spec["fill"], size))
    if name == "wait":
        # a 120-degree arc from twelve o'clock, centred on the ring
        cx, cy, r = RING
        arc = Image.new("L", m.size, 0)
        R = (r + 2) * s
        ImageDraw.Draw(arc).pieslice([cx * s - R, cy * s - R, cx * s + R, cy * s + R],
                                     -90, 30, fill=255)
        out.alpha_composite(paint(down(ImageChops.multiply(m, arc)), spec["arc"], size))
    return out, hot


def qoi_bytes(im):
    buf = io.BytesIO()
    im.save(buf, format="QOI")
    return buf.getvalue()


def image_theme(theme):
    """{path relative to the theme dir: bytes} for every shape and scale."""
    out = {}
    for name in GEOM:
        (w, h), _ = GEOM[name]
        files = []
        hot = None
        for k in SCALES:
            im, hot = render_image(theme, name, k)
            fname = f"{name}.qoi" if k == 1 else f"{name}@{k}x.qoi"
            out[fname] = qoi_bytes(im)
            files.append((k, fname))
        lines = [
            "# toy-os cursor shape -- generated by tools/gen_cursors.py",
            "# An IMAGE shape: straight-alpha ARGB in the QOI files named",
            "# below, one per scale. Its colours are its own.",
            f"shape={name}",
            f"width={w}",
            f"height={h}",
            f"hotspot={hot[0]},{hot[1]}",
        ]
        for k, fname in files:
            lines.append(f"image{'' if k == 1 else k}={fname}")
        out[name] = ("\n".join(lines) + "\n").encode()
    return out


def mask_shape(name, grow=0.0):
    """A GEOM shape as masks, for the mask themes: the fill's coverage and
    a one-pixel rim around it, cropped to the ink. `grow` thickens the
    stroke by that many 1x pixels -- bold's version, since dilating the
    finished masks closes the holes in `move` and `not-allowed`."""
    m, size, hot = geom_mask(name, 1)
    if grow:
        m = dilate(m, grow * SS)
    rim = dilate(m, SS)
    fill = m.resize(size, Image.BOX)
    ring = ImageChops.subtract(rim, m).resize(size, Image.BOX)
    bbox = Image.eval(ImageChops.lighter(fill, ring), lambda v: 255 if v else 0).getbbox()
    x0, y0, x1, y1 = bbox
    s = Shape(x1 - x0, y1 - y0, (hot[0] - x0, hot[1] - y0))
    # Coverage under a sixteenth is dropped rather than kept as a level-0
    # digit: bold dilates every pixel with ANY fill, and a faint fringe
    # would fatten it by a pixel more than the hand-drawn shapes.
    for y in range(s.h):
        for x in range(s.w):
            f = fill.getpixel((x + x0, y + y0))
            o = ring.getpixel((x + x0, y + y0))
            s.fill[y][x] = f if f >= 16 else 0
            s.outline[y][x] = o if o >= 16 else 0
    return s


def theme_default():
    return {
        "arrow": extract_arrow(),
        "resize-h": resize_shape("h"),
        "resize-v": resize_shape("v"),
        "resize-diag": resize_shape("diag"),
        "resize-diag2": resize_shape("diag2"),
        "text": ibeam(),
        "wait": hourglass(),
        "hand": mask_shape("hand"),
        "move": mask_shape("move"),
        "not-allowed": mask_shape("not-allowed"),
    }


def theme_bold():
    """A visibly different second theme, so switching is observable.

    Every shape is the default one dilated by a pixel -- a heavier
    pointer, which is also the accessibility reason a person would pick
    a different theme rather than only a different size.
    """
    out = {}
    for name, src in theme_default().items():
        if name in ("hand", "move", "not-allowed"):
            out[name] = mask_shape(name, grow=0.5)
            continue
        d = Shape(src.w + 2, src.h + 2, (src.hot[0] + 1, src.hot[1] + 1))
        for y in range(src.h):
            for x in range(src.w):
                if not src.fill[y][x]:
                    continue
                for dy in (0, 1, 2):
                    for dx in (0, 1, 2):
                        d.fill[y + dy][x + dx] = max(d.fill[y + dy][x + dx],
                                                      src.fill[y][x])
        for y in range(d.h):
            for x in range(d.w):
                if d.fill[y][x]:
                    continue
                near = any(0 <= y + dy < d.h and 0 <= x + dx < d.w and d.fill[y + dy][x + dx]
                           for dy in (-1, 0, 1) for dx in (-1, 0, 1))
                if near:
                    d.outline[y][x] = 255
        out[name] = d
    return out


THEMES = {"default": theme_default, "bold": theme_bold}


def theme_files(theme):
    """{filename: bytes} for one theme, whichever kind it is."""
    if theme in THEMES:
        return {name: shape.text(name).encode() for name, shape in THEMES[theme]().items()}
    return image_theme(theme)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any file would change")
    args = ap.parse_args()

    stale, written = [], 0
    for theme in list(THEMES) + list(IMAGE_THEMES):
        d = os.path.join(OUT_ROOT, theme)
        if not args.check:
            os.makedirs(d, exist_ok=True)
        for name, body in theme_files(theme).items():
            path = os.path.join(d, name)
            old = open(path, "rb").read() if os.path.exists(path) else None
            if old == body:
                continue
            if args.check:
                stale.append(os.path.relpath(path, REPO))
            else:
                open(path, "wb").write(body)
                written += 1

    if args.check:
        if stale:
            print("gen_cursors: STALE -- re-run tools/gen_cursors.py:")
            for p in stale:
                print(f"  {p}")
            return 1
        print("gen_cursors: up to date")
        return 0

    print(f"gen_cursors: wrote {written} file(s) under "
          f"{os.path.relpath(OUT_ROOT, REPO)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
