#!/usr/bin/env python3
"""Generate the seeded cursor themes under seed/sync/usr/share/cursors/.

A cursor shape is a plain-text file: a small key=value header plus two
coverage grids, one for the outline and one for the fill. The compositor
colours them at draw time, which is why the grids carry COVERAGE and not
colour -- one shape set then serves a light theme and a dark one, and
the two things people actually change (the shape and the colour) stay
independent. Same split X11's image+mask cursors have always had.

Why a generator rather than six hand-written files: the default theme's
arrow already exists as two anti-aliased C arrays in userland/wm/wm_render.c
and the three resize shapes already exist as procedural loops in the
same file. Re-typing either by hand is exactly the kind of transcription
this repo has been bitten by, so the arrow is EXTRACTED from the source
and the resize shapes are a port of the same loops. Run this after
changing either, and the shipped theme cannot drift from the built-in
fallback.

It is also the authoring tool: a new theme is a function here that
returns {shape name: Shape}, the same way tools/genfont.py is how a font
gets made rather than a thing anyone writes by hand.

    python3 tools/gen_cursors.py            # write the themes
    python3 tools/gen_cursors.py --check    # fail if they are stale (CI)
"""

import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WM_RENDER = os.path.join(REPO, "userland", "wm", "wm_render.c")
OUT_ROOT = os.path.join(REPO, "data", "cursors")

# One hex digit per pixel, so a 13-wide shape is 13 characters wide and
# a person can see the shape in the file. 16 levels is well past what a
# cursor needs and keeps the grid readable; '.' is a synonym for 0 so
# the drawn shape stands out from its background.
RAMP = "0123456789abcdef"


def to_char(alpha):
    if alpha <= 0:
        return "."
    return RAMP[min(15, (alpha * 15 + 127) // 255)]


class Shape:
    def __init__(self, w, h, hot=(0, 0)):
        self.w, self.h, self.hot = w, h, hot
        self.outline = [[0] * w for _ in range(h)]
        self.fill = [[0] * w for _ in range(h)]

    def text(self, name):
        lines = [
            "# toy-os cursor shape -- generated by tools/gen_cursors.py",
            "# Coverage per pixel, one hex digit (0-f); '.' is 0.",
            "# The compositor supplies the colours; these are masks.",
            f"shape={name}",
            f"width={self.w}",
            f"height={self.h}",
            f"hotspot={self.hot[0]},{self.hot[1]}",
            "outline=",
        ]
        lines += ["".join(to_char(a) for a in row) for row in self.outline]
        lines.append("fill=")
        lines += ["".join(to_char(a) for a in row) for row in self.fill]
        return "\n".join(lines) + "\n"


def extract_arrow():
    """The default arrow, taken from wm_render.c's own baked masks."""
    src = open(WM_RENDER).read()

    def grid(sym):
        m = re.search(
            r"cursor_%s_alpha\[CURSOR_SPRITE_H\]\[CURSOR_SPRITE_W\]\s*=\s*\{(.*?)\n\};" % sym,
            src, re.S)
        if not m:
            sys.exit(f"gen_cursors: could not find cursor_{sym}_alpha in {WM_RENDER}")
        rows = re.findall(r"\{([0-9,\s]+)\}", m.group(1))
        return [[int(v) for v in r.split(",")] for r in rows]

    out, fil = grid("outline"), grid("fill")
    h, w = len(out), len(out[0])
    s = Shape(w, h, (0, 0))  # the arrow's tip is its top-left pixel
    s.outline, s.fill = out, fil
    return s


# The resize arrow, ONE profile for all three directions. See
# wm_render.c's draw_resize_cursor(), which is the same arithmetic in C
# -- change both.
#
# Rasterised ANALYTICALLY rather than stepped along the axis: a stepped
# diagonal sets only pixels whose x+y is even, so the corner cursor came
# out a CHECKERBOARD, which is why it read as bigger and different from
# the edge ones. Scanning every pixel and asking how far along the arrow
# (u) and how far across it (v) it lies is solid in any direction, and
# makes the three the same arrow rotated rather than three constructions.
RZ_S = 256          # fixed point: 1 px
RZ_LEN = 19 * RZ_S  # tip to tip
RZ_HEAD = 5 * RZ_S  # of which each arrowhead
RZ_HW = 1152        # 4.5 px -- the head's half-width at its base
RZ_SW = 384         # 1.5 px -- the shaft's
RZ_DIAG = 181       # 256 / sqrt(2), so a diagonal arrow is 19 px long too


def rz_halfwidth(u):
    """Half the arrow's width at `u` along it, or -1 past either end."""
    if u < 0 or u > RZ_LEN:
        return -1
    if u < RZ_HEAD:
        return RZ_HW * u // RZ_HEAD
    if u > RZ_LEN - RZ_HEAD:
        return RZ_HW * (RZ_LEN - u) // RZ_HEAD
    return RZ_SW


def resize_shape(kind):
    """A double-headed arrow: outlined, 3 px shaft, 19 px tip to tip."""
    n = 34
    c = n // 2
    fill = [[0] * n for _ in range(n)]
    for y in range(n):
        for x in range(n):
            dx, dy = x - c, y - c
            if kind == "h":
                u, v = dx * RZ_S + RZ_LEN // 2, dy * RZ_S
            elif kind == "v":
                u, v = dy * RZ_S + RZ_LEN // 2, dx * RZ_S
            else:
                u, v = (dx + dy) * RZ_DIAG + RZ_LEN // 2, (dx - dy) * RZ_DIAG
            hw = rz_halfwidth(u)
            if hw >= 0 and abs(v) <= hw + RZ_S // 2:
                fill[y][x] = 1

    xs = [x for y in range(n) for x in range(n) if fill[y][x]]
    ys = [y for y in range(n) for x in range(n) if fill[y][x]]
    x0, x1 = min(xs) - 1, max(xs) + 1
    y0, y1 = min(ys) - 1, max(ys) + 1
    w, h = x1 - x0 + 1, y1 - y0 + 1

    s = Shape(w, h, (c - x0, c - y0))   # the hotspot is the arrow's centre
    for y in range(h):
        for x in range(w):
            if fill[y + y0][x + x0]:
                s.fill[y][x] = 255
    # Outlined all round, so it reads against a light window border --
    # the previous shape's middle was bare white and vanished there.
    for y in range(h):
        for x in range(w):
            if s.fill[y][x]:
                continue
            if any(0 <= y + dy < h and 0 <= x + dx < w and s.fill[y + dy][x + dx]
                   for dy in (-1, 0, 1) for dx in (-1, 0, 1)):
                s.outline[y][x] = 255
    return s


def ibeam():
    """A text cursor: a vertical bar with serifs, outlined for contrast."""
    s = Shape(7, 17, (3, 8))
    for y in range(1, 16):
        s.fill[y][3] = 255
    for x in range(1, 6):           # serifs, top and bottom
        s.fill[1][x] = 255
        s.fill[15][x] = 255
    # Outline every fill pixel's neighbours that are not themselves fill,
    # so the bar stays visible over text of any colour.
    for y in range(s.h):
        for x in range(s.w):
            if s.fill[y][x]:
                continue
            near = any(0 <= y + dy < s.h and 0 <= x + dx < s.w and s.fill[y + dy][x + dx]
                       for dy in (-1, 0, 1) for dx in (-1, 0, 1))
            if near:
                s.outline[y][x] = 255
    return s


def hourglass():
    """A wait cursor: an hourglass, drawn as two facing wedges."""
    s = Shape(11, 15, (5, 7))
    for y in range(15):
        if y in (0, 14):
            for x in range(1, 10):
                s.outline[y][x] = 255
            continue
        # Half-width shrinks to the waist at y=7 and grows again.
        half = 4 - abs(7 - y) * 4 // 7
        for x in range(5 - half, 5 + half + 1):
            s.fill[y][x] = 255
        if 5 - half - 1 >= 0:
            s.outline[y][5 - half - 1] = 255
        if 5 + half + 1 < s.w:
            s.outline[y][5 + half + 1] = 255
    return s


def theme_default():
    return {
        "arrow": extract_arrow(),
        "resize-h": resize_shape("h"),
        "resize-v": resize_shape("v"),
        "resize-diag": resize_shape("diag"),
        "text": ibeam(),
        "wait": hourglass(),
    }


def theme_bold():
    """A visibly different second theme, so switching is observable.

    Every shape is the default one dilated by a pixel -- a heavier
    pointer, which is also the accessibility reason a person would pick
    a different theme rather than only a different size.
    """
    out = {}
    for name, src in theme_default().items():
        d = Shape(src.w + 2, src.h + 2, (src.hot[0] + 1, src.hot[1] + 1))
        for y in range(src.h):
            for x in range(src.w):
                if not src.fill[y][x]:
                    continue
                for dy in (0, 1, 2):
                    for dx in (0, 1, 2):
                        d.fill[y + dy][x + dx] = max(d.fill[y + dy][x + dx],
                                                      src.fill[y][x])
        for y in range(d.h):
            for x in range(d.w):
                if d.fill[y][x]:
                    continue
                near = any(0 <= y + dy < d.h and 0 <= x + dx < d.w and d.fill[y + dy][x + dx]
                           for dy in (-1, 0, 1) for dx in (-1, 0, 1))
                if near:
                    d.outline[y][x] = 255
        out[name] = d
    return out


THEMES = {"default": theme_default, "bold": theme_bold}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any file would change")
    args = ap.parse_args()

    stale, written = [], 0
    for theme, build in THEMES.items():
        d = os.path.join(OUT_ROOT, theme)
        if not args.check:
            os.makedirs(d, exist_ok=True)
        for name, shape in build().items():
            path = os.path.join(d, name)
            body = shape.text(name)
            old = open(path).read() if os.path.exists(path) else None
            if old == body:
                continue
            if args.check:
                stale.append(os.path.relpath(path, REPO))
            else:
                open(path, "w").write(body)
                written += 1

    if args.check:
        if stale:
            print("gen_cursors: STALE -- re-run tools/gen_cursors.py:")
            for p in stale:
                print(f"  {p}")
            return 1
        print("gen_cursors: up to date")
        return 0

    print(f"gen_cursors: wrote {written} file(s) under "
          f"{os.path.relpath(OUT_ROOT, REPO)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
