#!/usr/bin/env python3
"""tools/gen_commands_index.py -- regenerate docs/commands/README.md's index.

WHY IT IS GENERATED
-------------------
Same reason `docs/decisions.md` is, and this script is deliberately the
same shape: an index kept true by someone remembering to add a line is
the shape of every convention this repo has had to delete. See
CLAUDE.md's "prefer facts that cannot go stale".

`tools/check_docs.py` fails the build when the committed index does not
match what this would produce, which is what makes "run this" a rule
rather than a hope. It already refuses a command with no page; this
refuses a page nobody can find.

WHERE THE CATEGORY COMES FROM
-----------------------------
The PAGE ITSELF: a `**Category:** ...` line near the top. Not a table in
this script -- that would be the central list the settings registry
deliberately does not have, where a new command means editing two files
and the one nobody edits is the table. A page owns its own placement,
which is the same argument `struct setting.category` already made.

A category nothing declares simply does not appear. A page with no
category line is reported rather than filed under a default, because
"General" would hide it in exactly the pile nobody reads.

WHAT IT DOES NOT TOUCH
----------------------
Everything above the marker -- the rules, what a page is for, how to add
a command. That is prose making an argument, and a generator that
rewrote it would own an argument it did not make.
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = os.path.join(REPO, "docs", "commands")
INDEX = os.path.join(PAGES, "README.md")
MARKER = "## Every command"

# The order categories appear in. A category not named here still gets a
# section, after these, so adding one to a page is enough to see it --
# this list only decides what comes FIRST, which is a judgement about
# what a reader is most likely looking for.
ORDER = [
    "Documentation",
    "Files and the filesystem",
    "System information",
    "Processes and programs",
    "Appearance and the console",
    "Configuration",
    "Disk and filesystem maintenance",
    "Developer and diagnostic (`help tests`)",
]


def pages():
    """(name, category, summary) for every page, sorted by name."""
    out = []
    for fn in sorted(os.listdir(PAGES)):
        if not fn.endswith(".md") or fn == "README.md":
            continue
        name = fn[:-3]
        text = open(os.path.join(PAGES, fn), encoding="utf-8").read()
        m = re.search(r"^\*\*Category:\*\*\s*(.+)$", text, re.M)
        out.append((name, m.group(1).strip() if m else None))
    return out


def build(entries):
    by_cat = {}
    for name, cat in entries:
        by_cat.setdefault(cat, []).append(name)
    seen = [c for c in ORDER if c in by_cat]
    seen += sorted(c for c in by_cat if c not in ORDER and c is not None)

    out = [MARKER, ""]
    out.append("<!-- Generated by tools/gen_commands_index.py -- do not edit")
    out.append("     below this marker by hand; the category comes from each")
    out.append("     page's own `**Category:**` line. -->")
    out.append("")
    for cat in seen:
        out.append(f"### {cat}")
        out.append("")
        for name in by_cat[cat]:
            out.append(f"- [`{name}`]({name}.md)")
        out.append("")
    return "\n".join(out)


def preamble():
    text = open(INDEX, encoding="utf-8").read() if os.path.exists(INDEX) else ""
    i = text.find(MARKER)
    return text[:i] if i >= 0 else (text.rstrip() + "\n\n")


def main():
    entries = pages()
    uncategorised = sorted(n for n, c in entries if not c)
    if uncategorised:
        print("gen_commands_index: no `**Category:**` line in: "
              + ", ".join(uncategorised))
        return 1

    want = preamble() + build(entries)
    have = open(INDEX, encoding="utf-8").read() if os.path.exists(INDEX) else ""
    if have == want:
        print("gen_commands_index: up to date")
        return 0
    if "--check" in sys.argv:
        print("gen_commands_index: docs/commands/README.md is STALE -- run "
              "tools/gen_commands_index.py")
        return 1
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(want)
    print(f"gen_commands_index: rewrote {os.path.relpath(INDEX, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
