#!/usr/bin/env python3
"""tools/gen_next_up.py -- regenerate the "Next up" section of docs/roadmap.md.

WHY THERE IS A SECOND AXIS AT ALL
---------------------------------
`docs/roadmap.md` is ordered by DEPENDENCY -- what must be built before
what -- which is what makes reading it top to bottom answer "what next"
for the phases. It deliberately does not encode PRIORITY, because a
total priority order would imply the tracks depend on each other when
they do not.

Urgency is therefore a different question from position, and the two
cannot share one ordering. So an item states its own urgency where it
LIVES, with a `**NEXT**` marker, and this script collects them.

WHY IT IS GENERATED
-------------------
The obvious alternative -- a hand-kept list at the top naming items by
title -- is exactly the shape of every maintenance burden this repo has
deleted: a pointer whose correctness depends on somebody remembering to
update a second place. Rename an item and the pointer rots silently.
See CLAUDE.md's "prefer facts that cannot go stale".

Derived instead: mark the item, run this, and the section is correct by
construction. `tools/check_docs.py` fails the build when the committed
section does not match what this would produce, which is what makes
"run this" a rule rather than a hope -- the same arrangement
`gen_decisions_index.py` already has.

WHAT A MARKER MEANS
-------------------
`**NEXT**` on a roadmap item means "do this before the unmarked work
around it", not "this is broken" -- something that MISBEHAVES belongs in
`docs/bugs.md`, which is a different list answering a different
question. An item keeps its own one-line text; this section adds the
section it came from, so a reader can see whether the queue is spread
across tracks or concentrated in one.

Usage:
    python3 tools/gen_next_up.py           # print what the section should be
    python3 tools/gen_next_up.py --write   # rewrite docs/roadmap.md in place
    python3 tools/gen_next_up.py --check   # exit non-zero if it is stale
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROADMAP = os.path.join(REPO, "docs", "roadmap.md")

BEGIN = "<!-- BEGIN next-up (generated by tools/gen_next_up.py) -->"
END = "<!-- END next-up -->"
MARKER = "**NEXT**"


def collect(text):
    """Every unfinished item carrying the marker, with the section it is in.

    Unfinished only: a `- [x]` line that still carried a marker would be
    a queue entry for work already done, which is the one thing an index
    like this must never show. Struck-through items keep their text, so
    the marker survives the tick unless someone removes it -- and nobody
    will remember to.
    """
    out = []
    section = "?"
    for line in text.splitlines():
        if line.startswith("### "):
            section = line[4:].strip()
        elif line.startswith("## ") and not line.startswith("## Next up"):
            section = line[3:].strip()
        if not line.startswith("- [ ] "):
            continue
        if MARKER not in line:
            continue
        item = line[len("- [ ] "):].strip()
        item = item.replace(MARKER, "").strip()
        # A marker at the head of a line leaves a stray separator behind.
        item = re.sub(r"^(--|—)\s*", "", item).strip()
        out.append((section, item))
    return out


def render(items):
    if not items:
        return ("Nothing is marked urgent. Mark an item with `**NEXT**` where it\n"
                "lives and re-run `tools/gen_next_up.py`.\n")
    lines = ["**Marked `**NEXT**` where they live, and collected here by",
             "`tools/gen_next_up.py`.** Urgency is not the same question as",
             "position: the sections below are ordered by what must be built",
             "FIRST, and this is what to do first among things that are all",
             "buildable now. Something that MISBEHAVES is not here -- that is",
             "`docs/bugs.md`.", ""]
    for section, item in items:
        lines.append(f"- [ ] {item}  *({section})*")
    lines.append("")
    return "\n".join(lines)


def main():
    text = open(ROADMAP).read()
    if BEGIN not in text or END not in text:
        print("gen_next_up: docs/roadmap.md has no next-up markers", file=sys.stderr)
        return 2
    body = render(collect(text))
    # DIRECTIONALLY, and asserting the invariant: a slice replaced by
    # index is how this repo once re-appended 2,673 lines to CLAUDE.md.
    start = text.index(BEGIN)
    end = text.index(END, start)
    assert end > start
    new = text[:start] + BEGIN + "\n" + body + text[end:]

    if "--check" in sys.argv:
        if new != text:
            print("gen_next_up: docs/roadmap.md's Next up section is stale",
                  file=sys.stderr)
            return 1
        return 0

    if "--write" in sys.argv:
        if new != text:
            open(ROADMAP, "w").write(new)
            print("gen_next_up: rewrote docs/roadmap.md")
        else:
            print("gen_next_up: docs/roadmap.md already current")
        return 0

    sys.stdout.write(body)
    return 0 if new == text else 1


if __name__ == "__main__":
    sys.exit(main())
