#!/usr/bin/env python3
"""build/gen/bootwords.h: every kernel boot word, from docs/boot-flags.md.

The boot words are matched by substring with no registry in the kernel,
so the table in docs/boot-flags.md is the only list there is
(that page's "Adding a flag"). `bootcfg` and the Boot Manager refuse a
word not on it, so the list is GENERATED from the page at parse time --
a flag documented there is accepted on the next build, and one that is
not documented cannot be offered.

Each row's first column is the word as typed (`video=<W>x<H>`,
`debugcon[=ttyS0]`, `kdebug=net,...`); the emitted KEY is the part a
word on a command line must start with (`video=`, `debugcon`, `kdebug=`)
and the HINT the rest. Rows sharing a key (the two `kdebug=` forms)
become one entry with the hints joined. The description is the Effect
column's first clause, markdown stripped.

Writes the file only when its content changed, so `make` rebuilds only
what includes it.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DOC = os.path.join(REPO, "docs", "boot-flags.md")

# Shouted words in the Effect column stay readable in a GUI row only
# lowercased; these are real acronyms and keep their case.
ACRONYMS = {"ACPI", "AHCI", "NVME", "MMIO", "KASLR", "ASLR", "GRUB", "USB",
            "TSC", "PIC", "APIC", "LAPIC", "PAT", "MTRR", "NCQ", "DSM", "GPE",
            "TRIM", "SATA", "IDE", "GDB", "HD", "ATA", "NIC", "PIT", "RAM",
            "PM", "PCI", "MSI", "CPU", "EC"}


def clean(text):
    text = text.replace("**", "").replace("`", "").replace("\\|", "|")
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)

    def lower(m):
        w = m.group(0)
        keep = w in ACRONYMS or any(c.isdigit() for c in w)
        return w if keep else w.lower()
    return re.sub(r"\b[A-Z][A-Z0-9]+\b", lower, text)


def first_clause(effect):
    s = clean(effect)
    cut = len(s)
    for sep in (". ", " -- ", " — ", " (", "; ", ": "):
        i = s.find(sep)
        if 0 < i < cut:
            cut = i
    s = s[:cut].rstrip(".").strip()
    return s[:1].upper() + s[1:]


def parse_rows(md):
    rows = []
    in_table = False
    for line in md.splitlines():
        if line.startswith("| Flag |"):
            in_table = True
            continue
        if not in_table:
            continue
        if not line.startswith("|"):
            break
        if line.startswith("|---"):
            continue
        cells = [c.strip() for c in re.split(r"(?<!\\)\|", line)[1:-1]]
        if len(cells) < 2:
            continue
        m = re.match(r"`([^`]+)`", cells[0])
        if not m:
            continue
        rows.append((m.group(1).replace("\\|", "|"), cells[1]))
    return rows


def split_word(spelled):
    # `video=<W>x<H>` -> ("video=", "<W>x<H>"); `debugcon[=ttyS0]` ->
    # ("debugcon", "[=ttyS0]"); `nokaslr` -> ("nokaslr", "").
    m = re.match(r"([a-z0-9_.]+=?)(.*)$", spelled)
    if not m:
        raise ValueError("cannot read boot word %r" % spelled)
    return m.group(1), m.group(2)


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(md):
    entries = {}
    order = []
    for spelled, effect in parse_rows(md):
        key, hint = split_word(spelled)
        if key not in entries:
            entries[key] = [[], first_clause(effect)]
            order.append(key)
        if hint:
            entries[key][0].append(hint)
    if len(order) < 10:
        raise ValueError("found only %d boot words -- has the table's shape changed?" % len(order))
    out = ["// GENERATED by tools/gen_bootwords.py from docs/boot-flags.md -- do not edit.",
           "// Included by userland/lib/ubootwords.c only.",
           "static const struct ubootword UBOOTWORDS[] = {"]
    for key in order:
        hints, desc = entries[key]
        out.append("    { %s, %s, %s }," % (c_str(key), c_str(" or ".join(hints)), c_str(desc)))
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", required=True)
    ap.add_argument("--print", action="store_true", help="also print the table")
    a = ap.parse_args()
    with open(DOC) as f:
        text = generate(f.read())
    old = None
    if os.path.exists(a.out):
        with open(a.out) as f:
            old = f.read()
    if old != text:
        os.makedirs(os.path.dirname(a.out), exist_ok=True)
        with open(a.out, "w") as f:
            f.write(text)
    if a.print:
        sys.stdout.write(text)


if __name__ == "__main__":
    try:
        main()
    except ValueError as e:
        print("gen_bootwords: %s" % e, file=sys.stderr)
        sys.exit(1)
