#!/usr/bin/env python3
"""signames.c for the dash port, from TOY-OS's signal numbers.

WHY THIS EXISTS, AND IT IS NOT ONLY THE LICENCE
-----------------------------------------------
dash ships `src/mksignames.c` to generate this table, and that file is
GPL-2-or-later from GNU Bash -- the one non-BSD file in an otherwise
BSD port (see `userland/ports/dash/README.md` and `LICENSE`). Its output
is LINKED, so using it would pull the GPL into the shell binary.

But the licence is the smaller reason. mksignames.c reads the HOST's
<signal.h> and emits whatever the host has -- so a dash built here would
carry Linux's signal set, and `kill -l` would list signals this kernel
has never heard of while missing the numbering it does use. The table
has to come from `kernel/include/abi/signal_abi.h`, which is the only
place that knows what a signal number means on this system.

WHAT IT EMITS
-------------
`const char *const signal_names[NSIG + 1]`, indexed by signal number.
Index 0 is "EXIT", which is not a signal at all: it is the shell's name
for the trap that runs at exit, and dash indexes this array with it
(`trap EXIT`). A number with no name gets a numeric placeholder rather
than NULL, because dash prints the entry unconditionally.

NOT A FIXED LIST. The names are parsed out of the header, so a signal
added there appears here on the next build -- which is the whole point
of generating it rather than writing it down twice.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
ABI = os.path.join(REPO, "kernel", "include", "abi", "signal_abi.h")

# `#define SIGFOO 13` -- and deliberately NOT `SIGNAL_MAX`, `SIG_DFL`,
# `SIG_BLOCK` or the SIGFRAME_* family, none of which is a signal.
DEFINE = re.compile(r"^#define\s+(SIG[A-Z0-9]+)\s+(\d+)", re.M)
NOT_SIGNALS = {"SIGNAL_MAX", "SIGNAL_ABI_H"}


def parse(path):
    src = open(path).read()
    out = {}
    for name, num in DEFINE.findall(src):
        if name in NOT_SIGNALS or name.startswith("SIGFRAME"):
            continue
        out[int(num)] = name[3:]          # strip the "SIG"
    m = re.search(r"^#define\s+SIGNAL_MAX\s+(\d+)", src, re.M)
    if not m:
        raise SystemExit("gen_signames: no SIGNAL_MAX in " + path)
    return out, int(m.group(1))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__)
    ap.add_argument("--abi", default=ABI, help="signal_abi.h to read")
    ap.add_argument("--out", required=True, help="signames.c to write")
    args = ap.parse_args()

    names, sigmax = parse(args.abi)
    if not names:
        raise SystemExit("gen_signames: no SIG* defines found -- has the "
                         "header's format changed?")

    lines = [
        "/* GENERATED by tools/gen_signames.py from",
        " * kernel/include/abi/signal_abi.h. Do not edit.",
        " *",
        " * Replaces dash's own src/mksignames.c, which is GPL-2 from bash",
        " * AND reads the HOST's signal set rather than this kernel's.",
        " */",
        "#include <signal.h>",
        "",
        "const char *const signal_names[NSIG + 1] = {",
        '    /* 0 */ "EXIT",   /* not a signal: the shell\'s exit trap */',
    ]
    for n in range(1, sigmax + 1):
        if n in names:
            lines.append(f'    /* {n:2d} */ "{names[n]}",')
        else:
            # A placeholder rather than NULL: dash prints the entry
            # without checking, and `kill -l` should show the gap rather
            # than dereference nothing.
            lines.append(f'    /* {n:2d} */ "{n}",')
    lines.append(f'    /* {sigmax + 1} */ 0,')
    lines.append("};")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"gen_signames: {len(names)} named signals, {sigmax + 1} entries "
          f"-> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
