#!/usr/bin/env python3
"""Generate the image data this repo ships: the test vectors and the wallpapers.

TWO OUTPUTS, ONE TOOL, because both are "a JPEG produced by libjpeg for
toy-os to read back" and splitting them would mean two scripts with the
same encoder settings to keep in step.

  --vectors     userland/tests/uimg_vectors.h -- small JPEGs as byte
                arrays, each with the RGB **libjpeg** decodes them to.
                That is the whole point of the file: /tests/uimg_test
                compares userland/lib/uimg_jpeg.c's output against a
                different implementation's, not against its own. A
                decoder tested only against itself is the AES-with-a-
                wrong-round-key problem docs/roadmap-details.md warns
                about -- self-consistent and worthless.

  --wallpapers  data/wallpapers/*.jpg -- the desktop backgrounds, drawn
                here rather than committed as somebody's photograph so
                the repo carries no image it does not own.

Both outputs are COMMITTED, like kernel/drivers/font_ttf.c and the
cursor themes: a checkout without Pillow still builds. Re-run this only
when the vectors or the wallpapers should actually change, and say so in
the commit message when you do.

Needs Pillow (see docs/tools.md's host-tools section).
"""
import argparse
import io
import math
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    sys.exit("gen_imgdata.py needs Pillow: pip install --user pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VECTORS_H = os.path.join(ROOT, "userland", "tests", "uimg_vectors.h")
WALLPAPER_DIR = os.path.join(ROOT, "data", "wallpapers")

# errno values from kernel/include/abi/errno.h, as POSITIVE numbers; the
# test compares them against a negative return.
EINVAL = 22
ENOTSUP = 95


def gradient(w, h):
    """A smooth two-axis gradient with a hard edge in it.

    Both halves matter. The gradient exercises the DC path and the
    chroma resampler; the hard edge is what produces large AC
    coefficients, so an IDCT with a wrong constant shows up there and
    nowhere else -- a decoder that only ever sees flat colour passes
    with the entire butterfly deleted.
    """
    im = Image.new("RGB", (w, h))
    px = im.load()
    for y in range(h):
        for x in range(w):
            r = 255 * x // max(1, w - 1)
            g = 255 * y // max(1, h - 1)
            b = 128 + 127 * int(math.sin(6.0 * x / max(1, w)) >= 0)
            if x > w // 2 and y > h // 2:
                r, g, b = 250, 12, 30       # the hard edge
            px[x, y] = (r, g, b)
    return im


def encode(im, **kw):
    buf = io.BytesIO()
    im.save(buf, format="JPEG", **kw)
    return buf.getvalue()


def c_bytes(name, data):
    out = ["static const unsigned char %s[] = {" % name]
    for i in range(0, len(data), 16):
        row = ", ".join("0x%02x" % b for b in data[i:i + 16])
        out.append("    %s," % row)
    out.append("};")
    return "\n".join(out)


def build_vectors():
    vectors = []

    def ok(name, im, **kw):
        data = encode(im, **kw)
        ref = Image.open(io.BytesIO(data)).convert("RGB")
        vectors.append({
            "name": name, "jpeg": data, "w": ref.width, "h": ref.height,
            "rgb": ref.tobytes(), "err": 0,
        })

    def bad(name, data, err):
        vectors.append({"name": name, "jpeg": data, "w": 0, "h": 0,
                        "rgb": None, "err": err})

    ok("rgb 4:4:4 q95", gradient(16, 16), quality=95, subsampling=0)
    ok("rgb 4:2:2 q90", gradient(24, 16), quality=90, subsampling=1)
    ok("rgb 4:2:0 q80", gradient(32, 24), quality=80, subsampling=2)
    # 17x9 is deliberately not a multiple of an MCU in either axis: the
    # decoder pads its planes out to whole MCUs and must crop back, and
    # an off-by-one there produces a picture with a garbage right/bottom
    # edge that a square test image cannot show.
    ok("partial MCU 17x9", gradient(17, 9), quality=85, subsampling=2)
    ok("grayscale", gradient(16, 16).convert("L"), quality=90)
    # Restart markers reset the DC predictor mid-scan. A decoder that
    # ignores them decodes the first interval correctly and then drifts,
    # so this vector fails in bands rather than everywhere.
    ok("restart markers", gradient(32, 32), quality=85, subsampling=2,
       restart_marker_rows=1)

    prog = encode(gradient(16, 16), quality=85, progressive=True)
    bad("progressive is refused", prog, ENOTSUP)
    truncated = vectors[2]["jpeg"][:len(vectors[2]["jpeg"]) * 6 // 10]
    bad("truncated is refused", truncated, EINVAL)
    bad("not an image", b"this is not a JPEG, not even slightly\n", EINVAL)

    return vectors


def write_vectors(vectors):
    out = ['// GENERATED by tools/gen_imgdata.py -- do not edit by hand.',
           '//',
           '// Each vector is a JPEG and the RGB **libjpeg** (through Pillow)',
           '// decodes it to. /tests/uimg_test decodes the same bytes with',
           '// userland/lib/uimg_jpeg.c and compares, which is the only way to',
           '// tell a correct decoder from a self-consistent one.',
           '#ifndef UIMG_VECTORS_H',
           '#define UIMG_VECTORS_H',
           '',
           'struct uimg_vector {',
           '    const char *name;',
           '    const unsigned char *jpeg;',
           '    unsigned jpeg_len;',
           '    int w, h;                  // expected size; 0 when err != 0',
           '    int err;                   // 0 = must decode; else the POSITIVE',
           '                               // errno the decoder must return',
           '    const unsigned char *rgb;  // w*h*3 reference pixels, or 0',
           '};',
           '']
    for i, v in enumerate(vectors):
        out.append(c_bytes("uimg_vec%d_jpeg" % i, v["jpeg"]))
        if v["rgb"] is not None:
            out.append(c_bytes("uimg_vec%d_rgb" % i, v["rgb"]))
        out.append("")
    out.append("static const struct uimg_vector uimg_vectors[] = {")
    for i, v in enumerate(vectors):
        rgb = ("uimg_vec%d_rgb" % i) if v["rgb"] is not None else "0"
        out.append('    { "%s", uimg_vec%d_jpeg, sizeof uimg_vec%d_jpeg, '
                   '%d, %d, %d, %s },' %
                   (v["name"], i, i, v["w"], v["h"], v["err"], rgb))
    out.append("};")
    out.append("")
    out.append("#define UIMG_VECTOR_COUNT "
               "((int)(sizeof uimg_vectors / sizeof uimg_vectors[0]))")
    out.append("")
    out.append("#endif")
    out.append("")
    with open(VECTORS_H, "w") as f:
        f.write("\n".join(out))
    total = sum(len(v["jpeg"]) for v in vectors)
    print("wrote %s: %d vectors, %d bytes of JPEG" %
          (os.path.relpath(VECTORS_H, ROOT), len(vectors), total))


# --- wallpapers -------------------------------------------------------
#
# 1280x720 is this project's default mode, so the common case needs no
# scaling at all. That was a real question rather than an obvious one --
# a half-size image would decode in a quarter of the time -- and it was
# settled by MEASURING instead: `imginfo -d` reports 50 ms for 960x540
# under TCG, so a full-size background costs the desktop about a tenth
# of a second at startup, once. At a different resolution uimg_scale()
# resamples it, which is what tools/hires_test.py's mode exercises.

def wallpaper_aurora(w, h):
    im = Image.new("RGB", (w, h))
    d = ImageDraw.Draw(im)
    for y in range(h):
        t = y / (h - 1)
        d.line([(0, y), (w, y)],
               fill=(int(10 + 26 * t), int(22 + 60 * t), int(46 + 78 * t)))
    for i in range(5):
        phase = i * 0.7
        amp = h * (0.05 + 0.02 * i)
        pts = []
        for x in range(0, w + 8, 8):
            u = x / w
            y = h * (0.30 + 0.09 * i) + amp * math.sin(6.3 * u + phase)
            pts.append((x, y))
        pts += [(w, h), (0, h)]
        d.polygon(pts, fill=(int(14 + 8 * i), int(60 + 14 * i), int(96 + 10 * i)))
    return im.filter(ImageFilter.GaussianBlur(9))


def wallpaper_dusk(w, h):
    im = Image.new("RGB", (w, h))
    d = ImageDraw.Draw(im)
    for y in range(h):
        t = y / (h - 1)
        d.line([(0, y), (w, y)],
               fill=(int(48 + 150 * (1 - t) ** 2), int(30 + 70 * (1 - t)),
                     int(60 + 40 * t)))
    d.ellipse([w * 0.62, h * 0.12, w * 0.62 + h * 0.30, h * 0.12 + h * 0.30],
              fill=(255, 214, 170))
    for i in range(4):
        base = h * (0.62 + 0.09 * i)
        pts = [(0, h), (0, base)]
        for x in range(0, w + 12, 12):
            u = x / w
            pts.append((x, base - h * 0.06 * math.sin(3.0 * u + i * 1.3) ** 2))
        pts.append((w, h))
        shade = 46 - 9 * i
        d.polygon(pts, fill=(shade, shade - 6, shade + 14))
    return im.filter(ImageFilter.GaussianBlur(2))


def build_wallpapers():
    os.makedirs(WALLPAPER_DIR, exist_ok=True)
    for name, fn in (("aurora", wallpaper_aurora), ("dusk", wallpaper_dusk)):
        im = fn(1280, 720)
        path = os.path.join(WALLPAPER_DIR, name + ".jpg")
        im.save(path, format="JPEG", quality=88, subsampling=2, optimize=True)
        print("wrote %s (%d bytes)" % (os.path.relpath(path, ROOT),
                                       os.path.getsize(path)))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vectors", action="store_true")
    ap.add_argument("--wallpapers", action="store_true")
    args = ap.parse_args()
    if not args.vectors and not args.wallpapers:
        args.vectors = args.wallpapers = True
    if args.vectors:
        write_vectors(build_vectors())
    if args.wallpapers:
        build_wallpapers()


if __name__ == "__main__":
    main()
