// GENERATED by tools/genttf.py -- do not edit.
//
// The Latin-1 codepoints baked after ASCII, and the ONE definition
// of them: kernel/lib is shared source, so ring 0 and ring 3 link
// the same bytes. See api/font_ttf.h for the counts.
#include "font_ttf.h"

const unsigned char font_ttf_extra_codepoints[FONT_TTF_EXTRA_COUNT] = {
    0xC4, 0xD6, 0xC5, 0xE4, 0xF6, 0xE5,
};
