// Loads /etc/kbs/<name> keyboard-layout data files, answers keyboard.c's
// keycode->character lookups, and composes DEAD KEYS -- see
// keyboard_layout.h's top comment for why this is split out of the
// driver itself.
//
// File format: plain lines, generated by tools/gen_kbs.py from Linux's
// own XKB data (that script's top comment has the whole grammar):
//
//   kc_<decimal evdev keycode>[_shift|_altgr|_shift_altgr]=<value>
//   kc_<keycode>...=dead:<accent>     the key is a dead key on that level
//   dead:<accent>=<value>             what the dead key types alone
//   dead:<accent>:<value>=<value>     dead key, then that char -> result
//
// <value> is a single literal byte, or `0x<hex>` for anything else (the
// Latin-1 letters, '=', ':', '#'). Lines starting with '#' after leading
// whitespace are comments; blank lines are ignored.
//
// This is deliberately its own small parser, NOT etc_config.c's: that
// one strips a trailing '#...' even on a key=value line, and here '#'
// can be a value ("kc_4_shift=#" for US Shift+3), and it trims trailing
// whitespace where the space bar's value is a literal " ".
//
// **A SYMBOL IS AN int, NOT A char.** A Latin-1 letter is 0x80-0xFF,
// negative in a signed `char` (this build has no -funsigned-char; see
// docs/decisions/drivers.md), and a dead key is above 0xFF. Every table
// below is uint16_t for that reason.
#include "keyboard_layout.h"
#include "fs.h"
#include "string.h"
#include "knum.h"

#define KB_LAYOUT_DIR "/etc/kbs/"

// INDEXED BY EVDEV KEYCODE, NOT BY AT SCANCODE: evdev is what every
// non-PS/2 keyboard reports natively, so no driver translates into a
// legacy encoding. The PS/2 driver translates its wire once, as Linux's
// atkbd does. See docs/decisions/drivers.md.
#define KB_KEYCODE_MAX 256

enum { LVL_BASE, LVL_SHIFT, LVL_ALTGR, LVL_SHIFT_ALTGR, LVL_COUNT };
static uint16_t g_table[LVL_COUNT][KB_KEYCODE_MAX];
static char g_current_name[KB_LAYOUT_NAME_MAX] = "us";

// --- dead keys -------------------------------------------------------
//
// The Linux console's shape (KDSKBDIACR's accent table, consulted by the
// keyboard driver), kept per layout and loaded from the layout's own
// file. Sized for Latin-1: the most compositions any one accent has
// there is a dozen.
#define KB_DEAD_MAX       8
#define KB_DEAD_NAME_MAX  12
#define KB_DEAD_PAIRS_MAX 24
struct kb_dead {
    char name[KB_DEAD_NAME_MAX];
    uint8_t spacing;                 // typed alone; 0 if the file gave none
    uint8_t npairs;
    uint8_t base[KB_DEAD_PAIRS_MAX];
    uint8_t result[KB_DEAD_PAIRS_MAX];
};
static struct kb_dead g_dead[KB_DEAD_MAX];
static int g_dead_count;

// The dead key waiting for its next key, as a symbol, or 0. Touched from
// the keyboard IRQ (every driver reaches it through key_event()) and
// cleared by a layout load.
static int g_pending;

static struct kb_dead *dead_lookup(const char *name, uint32_t len, int create) {
    if (len == 0 || len >= KB_DEAD_NAME_MAX) return 0;
    for (int i = 0; i < g_dead_count; i++)
        if (k_strlen(g_dead[i].name) == len && k_strncmp(g_dead[i].name, name, len) == 0)
            return &g_dead[i];
    if (!create || g_dead_count >= KB_DEAD_MAX) return 0;
    struct kb_dead *d = &g_dead[g_dead_count++];
    k_memset(d, 0, sizeof *d);
    k_memcpy(d->name, name, len);
    return d;
}

// Compiled-in last-resort US table -- applied only if /etc/kbs/us itself
// can't be read (no filesystem, corrupted disk, a skipped seed step).
static const char FALLBACK_US[128] = {
    0, 27, '1','2','3','4','5','6','7','8','9','0','-','=', '\b',
    '\t', 'q','w','e','r','t','y','u','i','o','p','[',']', '\n',
    0, 'a','s','d','f','g','h','j','k','l',';','\'','`',
    0, '\\', 'z','x','c','v','b','n','m',',','.','/', 0,
    '*', 0, ' ', 0,
};
static const char FALLBACK_US_SHIFT[128] = {
    0, 27, '!','@','#','$','%','^','&','*','(',')','_','+', '\b',
    '\t', 'Q','W','E','R','T','Y','U','I','O','P','{','}', '\n',
    0, 'A','S','D','F','G','H','J','K','L',':','"','~',
    0, '|', 'Z','X','C','V','B','N','M','<','>','?', 0,
    '*', 0, ' ', 0,
};

static void clear_tables(void) {
    k_memset(g_table, 0, sizeof g_table);
    g_dead_count = 0;
    g_pending = 0;
}

static void apply_fallback_us(void) {
    clear_tables();
    for (int i = 0; i < 128; i++) {
        g_table[LVL_BASE][i] = (unsigned char)FALLBACK_US[i];
        g_table[LVL_SHIFT][i] = (unsigned char)FALLBACK_US_SHIFT[i];
    }
}

// A value field: a single literal byte, or "0x<hex>". Returns the byte,
// or -1 if `value` (length `len`) is neither.
static int parse_value(const char *value, uint32_t len) {
    if (len == 1) return (unsigned char)value[0];
    if (len >= 3 && value[0] == '0' && (value[1] == 'x' || value[1] == 'X')) {
        int v = 0;
        for (uint32_t i = 2; i < len; i++) {
            int d = k_hex_digit(value[i]);
            if (d < 0 || v > 0xFF) return -1;
            v = (v << 4) | d;
        }
        return v <= 0xFF ? v : -1;
    }
    return -1;
}

static int has_prefix(const char *s, uint32_t len, const char *p) {
    uint32_t n = (uint32_t)k_strlen(p);
    return len >= n && k_strncmp(s, p, n) == 0;
}

// "dead:<name>=<v>" or "dead:<name>:<base>=<v>", `line` past "dead:".
static void apply_dead_line(const char *line, uint32_t len) {
    uint32_t n = 0;
    while (n < len && line[n] != '=' && line[n] != ':') n++;
    if (n >= len) return;
    struct kb_dead *d = dead_lookup(line, n, 1);
    if (!d) return;
    if (line[n] == '=') {
        int v = parse_value(line + n + 1, len - n - 1);
        if (v > 0) d->spacing = (uint8_t)v;
        return;
    }
    // ':' -- a composition. The base is one byte or 0x<hex>, never '='
    // (the generator writes '=' as 0x3D), so the first '=' ends it.
    const char *b = line + n + 1;
    uint32_t rest = len - n - 1, bl = 0;
    while (bl < rest && b[bl] != '=') bl++;
    if (bl >= rest) return;
    int base = parse_value(b, bl);
    int res = parse_value(b + bl + 1, rest - bl - 1);
    if (base <= 0 || res <= 0 || d->npairs >= KB_DEAD_PAIRS_MAX) return;
    d->base[d->npairs] = (uint8_t)base;
    d->result[d->npairs] = (uint8_t)res;
    d->npairs++;
}

// One already-isolated line (no trailing '\n'). Anything that doesn't
// match is ignored, the same tolerance etc_config.c has.
static void apply_line(const char *line, uint32_t len) {
    if (len > 0 && line[len - 1] == '\r') len--;   // a CRLF file
    uint32_t i = 0;
    while (i < len && k_isblank(line[i])) i++;
    if (i >= len || line[i] == '#') return;
    line += i;
    len -= i;

    if (has_prefix(line, len, "dead:")) { apply_dead_line(line + 5, len - 5); return; }

    // "kc_" + a DECIMAL evdev keycode -- `kc_` and decimal, where this
    // was once `sc_` and hex: a file in the old form parses to nothing,
    // which load_from_file() refuses rather than leaving a dead keyboard.
    if (!has_prefix(line, len, "kc_")) return;
    i = 3;
    uint32_t keycode = 0, digits = 0;
    while (i < len && line[i] >= '0' && line[i] <= '9') {
        keycode = keycode * 10 + (uint32_t)(line[i] - '0');
        if (keycode >= KB_KEYCODE_MAX) return; // refused, not wrapped
        i++;
        digits++;
    }
    if (!digits || keycode == 0) return;

    // Longest suffix first: "_shift" is a prefix of "_shift_altgr".
    int level = LVL_BASE;
    if (has_prefix(line + i, len - i, "_shift_altgr")) { level = LVL_SHIFT_ALTGR; i += 12; }
    else if (has_prefix(line + i, len - i, "_shift")) { level = LVL_SHIFT; i += 6; }
    else if (has_prefix(line + i, len - i, "_altgr")) { level = LVL_ALTGR; i += 6; }
    if (i >= len || line[i] != '=') return;
    i++;

    // NOT trimmed: the space bar's value is a literal " ".
    const char *value = line + i;
    uint32_t value_len = len - i;
    if (value_len == 0) return;

    if (has_prefix(value, value_len, "dead:")) {
        int idx = -1;
        struct kb_dead *d = dead_lookup(value + 5, value_len - 5, 1);
        if (d) idx = (int)(d - g_dead);
        if (idx >= 0) g_table[level][keycode] = (uint16_t)KB_SYM_DEAD(idx);
        return;
    }
    int v = parse_value(value, value_len);
    if (v > 0) g_table[level][keycode] = (uint16_t)v;
}

// Reads and applies /etc/kbs/<name>. Returns 1 if the file exists and
// mapped something, 0 otherwise (the caller falls back).
static int load_from_file(const char *name) {
    char path[32];
    uint32_t dir_len = (uint32_t)k_strlen(KB_LAYOUT_DIR);
    uint32_t name_len = (uint32_t)k_strlen(name);
    if (dir_len + name_len >= sizeof(path)) return 0; // refuse rather than truncate

    k_memcpy(path, KB_LAYOUT_DIR, dir_len);
    k_memcpy(path + dir_len, name, name_len);
    path[dir_len + name_len] = '\0';

    // Into memory this file owns (fs_read_into), never the backend's
    // staging buffer: a ring-3 syscall can preempt this parse. A layout
    // with four levels and its dead keys is ~5 KB; an oversize file is
    // refused.
    static char data[16384];
    uint32_t size = fs_read_into(path, data, sizeof data);
    if (size == 0) return 0;
    return keyboard_layout_load_text(data, size);
}

int keyboard_layout_load_text(const char *data, uint32_t size) {
    clear_tables();
    uint32_t pos = 0;
    while (pos < size) {
        uint32_t line_start = pos;
        while (pos < size && data[pos] != '\n') pos++;
        apply_line(data + line_start, pos - line_start);
        if (pos < size) pos++;
    }

    // **A LAYOUT THAT MAPS NOTHING IS NOT A LAYOUT.** Reporting success
    // would leave the keyboard typing nothing -- a dead machine from a
    // file that read perfectly (a disk carrying the old `sc_` form parses
    // to exactly this). Refusing sends the caller down the fallback path.
    for (int l = 0; l < LVL_COUNT; l++)
        for (int i = 0; i < KB_KEYCODE_MAX; i++)
            if (g_table[l][i]) return 1;
    return 0;
}

int keyboard_layout_load(const char *name) {
    if (load_from_file(name)) {
        k_strlcpy(g_current_name, name, sizeof g_current_name);
        return 1;
    }

    // Not found: /etc/kbs/us (unless that was the request), then the
    // compiled-in table. Either way the name says what is ACTIVE.
    if (k_strcmp(name, "us") != 0 && load_from_file("us")) {
        k_strlcpy(g_current_name, "us", sizeof g_current_name);
        return 0;
    }

    apply_fallback_us();
    k_strlcpy(g_current_name, "us", sizeof g_current_name);
    return 0;
}

const char *keyboard_layout_current(void) {
    return g_current_name;
}

int keyboard_layout_translate(uint16_t keycode, int shift, int altgr) {
    if (keycode >= KB_KEYCODE_MAX) return 0;
    // An unmapped AltGr slot falls through rather than eating the key:
    // level 4 -> level 3 -> Shift/base.
    if (altgr) {
        if (shift && g_table[LVL_SHIFT_ALTGR][keycode]) return g_table[LVL_SHIFT_ALTGR][keycode];
        if (g_table[LVL_ALTGR][keycode]) return g_table[LVL_ALTGR][keycode];
    }
    return g_table[shift ? LVL_SHIFT : LVL_BASE][keycode];
}

// Is `lo` a lowercase letter whose capital is `up`? ASCII, or Latin-1's
// 0xE0-0xFE (less the division sign), whose capitals sit 0x20 below.
static int case_pair(int lo, int up) {
    if (lo >= 'a' && lo <= 'z') return up == lo - 'a' + 'A';
    if (lo >= 0xE0 && lo <= 0xFE && lo != 0xF7) return up == lo - 0x20;
    return 0;
}

int keyboard_layout_translate_caps(uint16_t keycode, int shift, int altgr, int caps) {
    if (caps && keycode < KB_KEYCODE_MAX &&
        case_pair(g_table[LVL_BASE][keycode], g_table[LVL_SHIFT][keycode]))
        shift = !shift;
    return keyboard_layout_translate(keycode, shift, altgr);
}

int keyboard_layout_spacing(int sym) {
    if (!KB_SYM_IS_DEAD(sym)) return sym;
    int idx = sym - KB_SYM_DEAD_BASE;
    return idx < g_dead_count ? g_dead[idx].spacing : 0;
}

int keyboard_layout_compose(int sym, uint8_t out[2]) {
    int n = 0;
    if (!sym) return 0;
    if (!g_pending) {
        if (KB_SYM_IS_DEAD(sym)) { g_pending = sym; return 0; }
        out[n++] = (uint8_t)sym;
        return n;
    }

    int pending = g_pending;
    g_pending = 0;
    int spacing = keyboard_layout_spacing(pending);

    if (KB_SYM_IS_DEAD(sym)) {
        // The same dead key twice is its accent; a different one types
        // the first's accent and waits on the second.
        if (spacing) out[n++] = (uint8_t)spacing;
        if (sym != pending) g_pending = sym;
        return n;
    }
    // Backspace and Esc take the accent back, as GTK and macOS do.
    if (sym == '\b' || sym == 0x1B) return 0;
    if (sym == ' ') {
        if (spacing) out[n++] = (uint8_t)spacing;
        return n;
    }
    const struct kb_dead *d = &g_dead[pending - KB_SYM_DEAD_BASE];
    for (int i = 0; i < d->npairs; i++)
        if (d->base[i] == sym) { out[n++] = d->result[i]; return n; }
    // Not composable: the accent, then the key -- Windows' behaviour.
    if (spacing) out[n++] = (uint8_t)spacing;
    out[n++] = (uint8_t)sym;
    return n;
}

int keyboard_layout_dead_pending(void) { return g_pending; }
void keyboard_layout_compose_reset(void) { g_pending = 0; }
